### ISSUE TITLE
[Paladin] Removing buff - [Pursuit of Justice] and [Crusader Aura]

### ISSUE THREAD

**Issue by Nacho-k** [WoWManiaUK/Blackwing-Lair#3666] opened 2019-10-19 00:02 UTC
**Links:**
Pursuit of justice: https://cata-twinhead.twinstar.cz/?spell=26023
Crusader aura: https://cata-twinhead.twinstar.cz/?spell=32223

**What is happening:**

Crusader aura is removing the 15% movement speed increase from pursuit of justice, and you only get it back if you relog after changing aura.

**What should happen:**

Crusader aura should'nt remove the dismounted movement speed

**Comment by Echinaceax** [comment] 2019-10-19 00:26
Nacho-k correct me if i read this wrong but they say in the link you shared that they dont stack 

![no stack](https://user-images.githubusercontent.com/39439201/67135209-abae3080-f217-11e9-8041-a27329527c1d.jpg)
![no stacking](https://user-images.githubusercontent.com/39439201/67135212-af41b780-f217-11e9-89b6-01ecabb641fa.jpg)

or am i missing something?

**Comment by Nacho-k** [comment] 2019-10-19 00:30
Crusader aura only provides mounted speed, pursuit of justice gives mounted and non-mounted movement speed.

**Comment by sarahkay88** [comment] 2019-10-19 10:16
Because it does stack, crusador  aura will over ride it no matter what because its a higher speed buff.

**Comment by sarahkay88** [comment] 2019-10-19 10:24
https://wowwiki.fandom.com/wiki/Crusader_Aura
It doesn't matter that the other movement speed provided ground speed as well and mounted speed, if u have the aura active it will still over ride it.

**Comment by sarahkay88** [comment] 2019-10-19 10:31
![Screenshot_20191019-112727](https://user-images.githubusercontent.com/42302580/67143502-f6ee3080-f263-11e9-903e-e3926c1d2969.png)

**Comment by Nacho-k** [comment] 2019-10-19 13:09
Crusader aura still overrides the non mounted movement speed for some reason, but because it doesnt give any non mounted movement speed, it deletes the 15% from pursuit of justice, an even then you still have to relog to get it back.
Please im not talking about the mounted movement speed

**Comment by sarahkay88** [comment] 2019-10-19 13:33
It doesn't matter that the other movement speed provided ground speed as well and mounted speed, if u have the aura active it will still over ride it. - doesn't matter if u still have both activated then the aura over takes the other - hence y it removes ur ground speed

**Comment by Nacho-k** [comment] 2019-10-19 13:36
okay let's say crusader aura should remove your dismounted speed, that speed doesnt come back if you    change aura, you have to relog to get that 15% movement speed increase back.

**Comment by sarahkay88** [comment] 2019-10-19 13:37
then that is a completely separate issue, that issue would be that the effects of the aura do not change.

**Comment by Nacho-k** [comment] 2019-10-19 13:38
i did, in this post

**Comment by sarahkay88** [comment] 2019-10-19 13:38
1 report per bug

**Comment by Nacho-k** [comment] 2019-10-19 14:26
I still cant find a reason why Ca should over ride Poj's dismounted movement speed, the screenshot you sent only talks about mounted speed. Your example with stamina scrolls works like that because they are both stamina buffs, Ca is only a mounted speed buff, while poj is both mounted and dismounted movement speed buff. They should be handled like different stats.

**Comment by sarahkay88** [comment] 2019-10-19 17:14
ur missing the main bit which is This effect does not stack with other movement speed increasing effects.
both are movement speed effect this is why! doesn't matter whether mounted or not!

**Comment by sarahkay88** [comment] 2019-10-19 17:19
this is getting over crowded keader is assigned n will take a look and decide what to do. :)

**Comment by Nacho-k** [comment] 2019-10-19 17:20
It matters, i dont know why you think mounted and dismounted speed should interfere with eachother, Blizzard was always really clear with it, thats why it always differentiates movement speed from mounted movement speed, if it didnt mattered poj description would only say, movement speed, pitching them both together.

**Comment by sarahkay88** [comment] 2019-10-19 17:26
dude seriously it will be looked at, it isn't like I closed ur report is it? it states it on both links u provide doesnt give a description of saying mounted/unmounted - this is ur evidence n it clear states any form of movement speed. correct me if im wrong, but both are movement speed effects.! I will not be replying as I said its over crowded let keader take a look and see what he determins

**Comment by bagi84** [comment] 2019-10-19 17:43
ive just checked this and crusader aura does overwrite the PoJ talent as it should but it doesn't revert once you remove the aura so the issue is defiantly spell/aura related.

**Comment by sarahkay88** [comment] 2019-10-19 17:44
#3669 - fresh report with correct info

**Comment by sarahkay88** [comment] 2019-10-19 17:58
more info for keaader when he comes https://www.wowhead.com/forums&topic=72987/is-crusaders-aura-really-suppose-to-increase-flying-mounts-speed
u have to scroll in the comments tho :)

**Comment by Kitzunu** [comment] 2019-12-20 09:47
this has also regressed i hear

**Comment by mfranca0009** [comment] 2021-02-12 05:30
Could we get someone to make sure this is still an issue? @Echinaceax

**Comment by golosomie** [comment] 2021-02-12 19:30
@mfranca0009 Confirmed on PTR that this is still bugged.
Once you activate Crusader aura, the movement speed increase from Pursuit of Justice is removed until the next relog.

**Comment by mfranca0009** [comment] 2021-02-14 18:06
This is all set, once the crusader aura is removed, Pursuit of Justice (Rank 1 / 2) will be re-applied to the player.

**Comment by golosomie** [comment] 2021-02-14 23:03
@mfranca0009 Confirmed fixed on PTR for both ranks of Pursuit of Justice.

**Closed** 2021-02-24 14:04 UTC
Labels: Class/Spells, Confirmed By Tester, Fixed Confirmed, Fixed in Dev, Regression
