### ISSUE TITLE
[NPC] Isabel Jones - ID 50480 Stormwind City

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Blackwing-Lair#1056] opened 2019-03-26 14:49 UTC
**Links:**
https://www.wowhead.com/npc=50480/isabel-jones

**What is happening:**
![Screenshot_4](https://user-images.githubusercontent.com/43518434/55006672-68bc0f80-4fde-11e9-8dac-446d0e304cf7.png)
I can see and take the quests from the Jewelcrafting trainer even tho i dont have Jewelcrafting trained at all
Also showing the same quest x2 while you can only grab it once.

**What should happen:**
I should not be able to see/take those those quests unless i have learned Jewelcrafting.

**Comment by Rushor** [comment] 2019-04-16 21:28
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/1129

**Closed by Rushor** 2019-04-16 21:28 UTC
Labels: Major City, Priority zone 1-20
