### ISSUE TITLE
[Quest] Champions call -12974-  Zul'Drak

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#215] opened 2018-12-19 10:30 UTC
quest - https://www.wowhead.com/quest=12974/the-champions-call
NPC - https://www.wowhead.com/npc=30137
This quest should start the quest chain for arena in Zul'drak - I am level 77 so requested assistance from a level 85 to complete the arena. However after handing in the champion Call quest I am unable to pick up the next quest has it did not display for me, but did for the level 85 player which should have activated the quest for me to part take. Instead said I did not meet the requirement's for this quest. I am the correct level and handed in the relevant quest.

![world of warcraft 19_12_2018 10_11_47](https://user-images.githubusercontent.com/42302580/50214784-06b59380-0379-11e9-8528-d9cf428a0032.png)
![Uploading World of Warcraft 19_12_2018 10_11_4
![Uploading World of Warcraft 19_12_2018 10_17_42.png
![world of warcraft 19_12_2018 10_17_46](https://user-images.githubusercontent.com/42302580/50214800-103efb80-0379-11e9-830d-3316ca46ae54.png)
…]()
7.png…]()

**Comment by Dranah** [comment] 2019-01-19 05:52
Cannot reproduce. I get the follow up quests at lvl 75 as intended.

**Comment by Dranah** [comment] 2019-05-05 23:15
This is happening on BWL, but i've still no idea how to reproduce on PTR. 
All we know is that it considers some players to not meet requirement despite being correct level, and having handed in the pre-quest, The Champion's call.

**Comment by Kitzunu** [comment] 2019-05-05 23:16
I might have an idea, will look into it tomorrow

**Comment by Dranah** [comment] 2019-05-08 00:09
I found the problem.
Completing the Ring of Blood series in Nagrand seems to close this other chain for no reason.
**How it should work:** doing the Ring of Blood quests (ending with https://www.wowhead.com/quest=9977/the-ring-of-blood-the-final-challenge) should not close the quest https://www.wowhead.com/quest=12932/the-amphitheater-of-anguish-yggdras)
**How it works atm**: doing the ring of blood quests seems to close the first one in the amphitheater, making you "not meet the requirements" to pick it up.
Once a GM adds the quest to you, and you complete it, there is no problem continuing the chain, so the only quest that is problematic is the first https://www.wowhead.com/quest=12932/the-amphitheater-of-anguish-yggdras

**Comment by wow-mania** [comment] 2019-05-11 14:09
Cannot reproduce.

**Comment by Dranah** [comment] 2019-05-12 15:55
Well, I can.
**Steps to repro:**
1) Pickup prequest https://www.wowhead.com/quest=12974/the-champions-call
2) Port to amphitheater. Now you can see you can hand this one to the NPC, who also needs to start the first part of Amphi chain
![WoWScrnShot_051219_174812](https://user-images.githubusercontent.com/31132743/57584651-21caa080-74de-11e9-928c-a272d5078e5c.jpg)
3) Once completed, the NPC offers the quest https://www.wowhead.com/quest=12932/the-amphitheater-of-anguish-yggdras for you as intended. This proves the quest is normally accessible if you meet the requirements.
![WoWScrnShot_051219_174912](https://user-images.githubusercontent.com/31132743/57584679-46267d00-74de-11e9-8af7-b70f0a86c043.jpg)
4) Now to go Ring of Blood in Nagrand and do the chain starting with https://www.wowhead.com/quest=9962/the-ring-of-blood-brokentoe
![WoWScrnShot_051219_174954](https://user-images.githubusercontent.com/31132743/57584701-9d2c5200-74de-11e9-9545-fd73fb0bac85.jpg)
5) This chain is finished when you have handed in https://www.wowhead.com/quest=9977/the-ring-of-blood-the-final-challenge
![WoWScrnShot_051219_175449](https://user-images.githubusercontent.com/31132743/57584735-0dd36e80-74df-11e9-8551-820908e7bb2e.jpg)
6) Now go back to Amphitheather and see if you can still take the quest to begin that chain.
BUMMER! You cant! The quest disappeared, completing the other chain in the other area has closed this one and made you impossible to access it (cannot be done via sharing from party either)
![WoWScrnShot_051219_175510](https://user-images.githubusercontent.com/31132743/57584742-2a6fa680-74df-11e9-8ed1-7501cae8a359.jpg)

**Comment by Kitzunu** [comment] 2019-05-28 14:32
test now

**Comment by Dranah** [comment] 2019-05-28 16:05
Looks good, same character can now see the quest again.

**Closed** 2019-06-01 08:08 UTC
Labels: Confirmed, Fixed Confirmed, Fixed in Dev, Legacy (wotlk)
