### ISSUE TITLE
[Quest] 25792 | Pushing Forward - Dun Morogh

### ISSUE THREAD

**Issue by iTz-AddriX** [WoWManiaUK/Blackwing-Lair#4311] opened 2020-03-29 20:22 UTC
**Links:** https://www.wowhead.com/quest=25792/pushing-forward

**What is happening:** Animation works only when using item.

**What should happen:** When using the item "Rune of Fire" it supposed to burn the Totems down.

**Comment by Kadajj** [comment] 2020-04-11 18:04
item works! it's not burning the Construction Totem. 

![WoWScrnShot_041120_190314](https://user-images.githubusercontent.com/38867875/79051269-32702300-7c27-11ea-8796-9f0c1fce78e5.jpg)

**Comment by rzenne** [comment] 2020-04-16 03:55
Tried to do the quest today. Still not working

**Comment by mfranca0009** [comment] 2020-07-08 18:01
Duplicate of #824

**Closed by mfranca0009** 2020-07-08 18:01 UTC
Labels: Confirmed By Tester, Starting Zone
