### ISSUE TITLE
[Quest] Fly over - ID 27008 / 27006 - Deepholm

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#276] opened 2018-12-21 18:16 UTC
Quest - https://www.wowhead.com/quest=27008/fly-over
NPC -https://www.wowhead.com/npc=44818
Flew over the gate, sat on the gate but the the gate does not register this cannot be completed.
![world of warcraft 21_12_2018 18_14_04](https://user-images.githubusercontent.com/42302580/50357072-90698a80-054c-11e9-8529-ca18866c4420.png)

**Comment by Eirolla** [comment] 2019-08-02 11:37
Tested on 02/08/19 Still, have an issue.

**Comment by Sammy974** [comment] 2019-08-12 15:10
Can confirm on 12/08/19

**Comment by Bathelmo** [comment] 2019-09-07 10:29
An ancient deepholm ticket? oh boi!

**Comment by Rushor** [comment] 2019-10-28 16:23
fixed

![I](https://i.imgur.com/cs1tLgY.jpg)

**Comment by sarahkay88** [comment] 2019-11-23 14:45
![WoWScrnShot_112319_144357](https://user-images.githubusercontent.com/42302580/69480501-c4ee6200-0dff-11ea-9c03-756af5feb139.jpg)
just did this quest on live today still not working :(

**Comment by mfranca0009** [comment] 2020-07-07 19:34
Is this still an issue? At the moment on PTR, it gives credit.

**Comment by Echinaceax** [comment] 2020-07-07 20:49
yes still an issue on live @mfranca0009

**Comment by mfranca0009** [comment] 2020-07-07 21:07
@Echinaceax Okay, will try to make an SQL file shortly and just wait till it's pushed to live to see if the problem is fixed

**Comment by Echinaceax** [comment] 2020-07-14 20:43
fix confirmed for both Ally and horde (in dev)

![completed](https://user-images.githubusercontent.com/39439201/87474461-68a4b080-c623-11ea-8a90-c8f2bc526d02.jpg)
![confirmed ally](https://user-images.githubusercontent.com/39439201/87474980-419aae80-c624-11ea-9e19-e3ad0e1f5564.jpg)

**Comment by Echinaceax** [comment] 2020-08-12 09:55
@mfranca0009 still an issue sadly 
GM just told me 

player was Ally
GM tested Horde 

both not working

**Comment by mfranca0009** [comment] 2020-08-12 14:13
Okay will take a look again

**Comment by Echinaceax** [comment] 2020-08-22 06:36
### Update for @mfranca0009 

- [x] Horde 27008 (fixed)
- [x] Ally 27006 (not fixed)

**Comment by mfranca0009** [comment] 2020-11-16 03:22
Made new script for the credit trigger, works now for Horde and Alliance with no issues 👍

**Comment by Echinaceax** [comment] 2020-11-16 03:28
confirmed fixed in PTR 
horde and Alliance

**Closed** 2020-11-18 11:41 UTC
Labels: Confirmed By Tester, Fixed Confirmed, Fixed in Dev, Regression, zone 80-85 Cata
