### ISSUE TITLE
[Boss] Helix Gearbreaker - Deadmines

### ISSUE THREAD

**Issue by Healwho** [WoWManiaUK/Blackwing-Lair#213] opened 2018-12-19 09:06 UTC
https://www.wowhead.com/npc=47296/helix-gearbreaker
This boss is a two part encounter. First being on the back of a pal and second he jumps to a random party member and is targeted to be killed.
The issue here is that he is not targetable by any member of the group and as such you cant kill him.
![wowscrnshot_121918_025616](https://user-images.githubusercontent.com/45921854/50210116-56796800-0343-11e9-97cb-2043ca4b2252.jpg)
![wowscrnshot_121918_025617](https://user-
images.githubusercontent.com/45921854/50210122-58dbc200-0343-11e9-8c9e-0914e595f64c.jpg)

**Comment by Kitzunu** [comment] 2019-03-10 20:12
Duplicate of #794

**Closed by Kitzunu** 2019-03-10 20:12 UTC
Labels: Confirmed
