### ISSUE TITLE
[NPC] Slim Shady dealer - Mana tombs

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4584] opened 2020-06-29 22:39 UTC
**Links:**

https://wowwiki.fandom.com/wiki/%22Slim%22
https://cata-twinhead.twinstar.cz/?npc=19679

**What is happening:**
- NPC has no sales window
_he has icon for vendor but no window_

**What should happen:**
_"Slim" is a level 63 general goods, reagent, poisons, meat and drink vendor located at the Mana Tombs entrance in the contested territory of Terokkar Forest._

![no sales window](https://user-images.githubusercontent.com/39439201/86063064-4b3fe600-ba6a-11ea-92df-1b609a9e5259.jpg)

**Comment by mfranca0009** [comment] 2021-02-13 05:41
Made some changes, because original script wasn't using the existing gossip from database.

BUT, there isn't an issue with this vendor, you need to have friendly or higher reputation rating with "The Consortium" (ID 933) to access his shop.

His npc text in the gossip window reflects this, because when you have the proper reputation rating he says "Ah, I see you are a friend to the Consortium. Perhaps you would be interested in making a purchase?" and then shows the vendor option.

**Comment by golosomie** [comment] 2021-02-13 16:09
@mfranca0009 Confirmed fixed on your TR. Now has vendor option only when friendly or higher with The Consortium.

**Closed as completed** 2021-02-24 14:04 UTC
Labels: Fixed in Dev - Ready to test, Fixed in Dev - Confirmed by tester
