### ISSUE TITLE
Public guild notes don't stay.

### ISSUE THREAD

**Issue by NoraDR** [WoWManiaUK/Blackwing-Lair#2733] opened 2019-07-13 11:01 UTC
I and many members of my guild have an issue where if you set your note and close out of the guild interface it will disappear and you will have no note set.

Here is a video of it.
https://cdn.discordapp.com/attachments/446681782926966795/599555451583070227/World_Of_Warcraft_2019.07.13_-_12.57.18.06.mp4

**Comment by Rushor** [comment] 2019-07-13 14:40
Are you the leader of the guild?

**Comment by NoraDR** [comment] 2019-07-13 14:43
> Are you the leader of the guild?

I am not only a offi

**Comment by Kitzunu** [comment] 2019-07-13 17:40
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/1874

**Closed by Kitzunu** 2019-07-13 17:40 UTC

**Comment by NoraDR** [comment] 2019-07-13 17:43
> duplicate of #1874

No, because this isn't me trying to set the note. It's people setting their own notes, as seen in the provided video I set my own note it didn't go to officer note it just didn't show at all...

**Comment by NoraDR** [comment] 2019-07-13 18:11
> duplicate of #1874

Are you serious you still closed it even after I explained why it isn't a dup? BRUH i thought you wanted to fix the bugs not just ignore their existence

**Comment by Kitzunu** [comment] 2019-07-13 18:36
1. it was closed before you commented.
2. add the info you have to that report since it regards the same part of the core.
