### ISSUE TITLE
[Map] Quests not displaying

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#136] opened 2018-11-27 13:28 UTC
Daily quests are not displayed on map on any level (Stromwind, elwynn forest, estern kingdom, world map not sure should this have displayed eather)

![map quest](https://user-images.githubusercontent.com/20323863/49084723-91aade80-f250-11e8-83fd-3797e6dd2af1.png)
![map quest 2](https://user-images.githubusercontent.com/20323863/49084729-98395600-f250-11e8-8045-bbf1a269db30.png)

**Comment by wow-mania** [comment] 2018-11-27 17:08
Unless we have a list of the quests we can't do much about it. They should show only on the mini map and the map show objectives only.

**Comment by TheSale** [comment] 2018-11-29 20:37
I will upload more ss of daily quests, but now it seems that there are more map-quest issues.
I dont know how in bloodmyst islands I had everything work fine with this, but regular quests dont show anythinting in Duskwood, or in Redridge mountains... I dont see guest objectives or end of quests on map, and minimap dont show it also and it should.

here is ss of quest not displayed on map or minimap in Redrifge Mountain
quest is active and I have to kill those mobs.
![redridge](https://user-images.githubusercontent.com/20323863/49249971-f4050a00-f41d-11e8-9147-db821902fffe.jpg)

here is quest receiver or end of quest displayed on map as it should work for every quest.
![guest receiver](https://user-images.githubusercontent.com/20323863/49250039-26166c00-f41e-11e8-814b-cfdc83d72fc2.png)

and here is displayed how objectives should be displayed on minimap as well, and if I am not in range for that quest objective, there should be arrow showing direction where should I go (similar to party member arrow when he is not in range of minimap just arrow of different color)
![minimap quest](https://user-images.githubusercontent.com/20323863/49250066-3890a580-f41e-11e8-868d-43b8cb506004.jpg)

and next 2 ss are 8 quest active in Duskwood but not displayed on map or in minimap
![wowscrnshot_112918_041125](https://user-images.githubusercontent.com/20323863/49250264-b5bc1a80-f41e-11e8-9e42-9554ca1373ec.jpg)
![wowscrnshot_112918_041133](https://user-images.githubusercontent.com/20323863/49250339-ddab7e00-f41e-11e8-89d7-b4f997bba933.jpg)

**Comment by TheSale** [comment] 2018-11-29 20:41
I added priority to this as it is not only daily quest issue only, this will slow down questing, and almost make  some quest objectives impossible to find without using addons or spend time googling it.

**Comment by wow-mania** [comment] 2018-11-29 20:47
Not a priority since this is just visual and does not stop you from completing the quests.

**Comment by TheSale** [comment] 2018-11-30 05:21
I totally agree with you that is just esthetic, but trust me it is more important than you think, and I will tell and show you why.
-First, people are lazy AF, nobody read quests (me included)

-Second, it save so much of time 1st you dont have to read quest, 2nd you can avoid problems to missread or to go on wrong location for wrong quest

-Third, it guide you so you dont get carried away with killing and walk away from zone where the mobs that you need to kill are

-Fourth, if you arrive to location where objective is, and you dont find it, you can open ticket for GM, or you can open map and see that mob has route where he walk.

-Fiftieth and example:
if you are let say new to horde, and you get quest to go to Ratchet then you get quest to go to the Sepulcher... on your own you will never know where are those locations, because you never have explored them so you cant even read on map. This is old totem quest for shaman, people even with quest helper on map had problems to complete it.

my current state
as a regular player yesterday when I died over 40 times I was lvl 22, same time today I am lvl 25, I did questing for maybe 4 hours and got only 3 levels, because I had to read each quest couple times to see where to go, and what is objective, and to recheck when I arrive there. for same time I would get at least 8 levels with map aid.

I have 8 quests open and I finished ones in Kruzen`s compound, now where to go?
If quest say go to Grom`gol base camp, and deliver this item to some guy, I have no clue where is that.
![where to go](https://user-images.githubusercontent.com/20323863/49269218-1f124c80-f464-11e8-9b6c-9e78edea2c08.png)

23 quests open I am tracking all and not one is displayed in 3 zones
![where to go 2](https://user-images.githubusercontent.com/20323863/49269219-233e6a00-f464-11e8-9f1b-c0eab4ae4cb2.png)
![where to go 3](https://user-images.githubusercontent.com/20323863/49269221-23d70080-f464-11e8-98ce-be90a7cc06ed.png)

I dont know where to go and what quest I should do
this gloving objective on floor I saw by pure accident when I was checking for treasure chests inside building.
![where to go 3](https://user-images.githubusercontent.com/20323863/49269767-f3dd2c80-f466-11e8-8052-e73d8fb61621.png)


as some things may look irrelevant and not important for some players they are very core of what they want from game. And they expect what they should get from current expansion or more, nobody will be satisfied with less.
this is just my point of view as one of the players.
and I ask for targeted issues and what to test, you only said crashes (that I never had :D ) and quests...
Well I cant do quest if I dont know where to go and what to do. :)

**Comment by Echinaceax** [comment] 2019-01-02 19:23
After completing the quest above, the next set of quests in Galens Fall a lvl24 are not tracking.

![galens fal mapl](https://user-images.githubusercontent.com/39439201/50608213-44173680-0ecc-11e9-8514-b9d0d064fbb1.jpg)

**Comment by Kitzunu** [comment] 2019-03-10 20:05
Duplicate of #870

**Closed by Kitzunu** 2019-03-10 20:05 UTC
Labels: Confirmed, starting-zone
