### ISSUE TITLE
[NPC] Lieutenant Horatio Laine (quest order) - Westfall

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4461] opened 2020-05-04 17:16 UTC
**Links:**

https://www.wowhead.com/npc=42308/lieutenant-horatio-laine

**What is happening:**
- npc quest order 
- player are given x2 https://www.wowhead.com/quest=26213/hot-on-the-trail-the-riverpaw-clan

**order given atm is** from wowhead 

![completed these 2](https://user-images.githubusercontent.com/39439201/80998220-d9209b80-8e42-11ea-9ff1-502e8bf1eb95.jpg)

https://www.wowhead.com/quest=26213/hot-on-the-trail-the-riverpaw-clan (once)
https://www.wowhead.com/quest=26214/hot-on-the-trail-murlocs
https://www.wowhead.com/quest=26213/hot-on-the-trail-the-riverpaw-clan (twice) 
https://www.wowhead.com/quest=26215/meet-two-shoed-lou
https://www.wowhead.com/quest=26228/livin-the-life
https://www.wowhead.com/quest=26232/lous-parting-thoughts

**What should happen:**
_According too our armory_ http://cata.cavernoftime.com/quest=26213

![cavenoftime](https://user-images.githubusercontent.com/39439201/80998311-09683a00-8e43-11ea-924f-d47c34f1368d.jpg)

**Hot On the Trail: The Riverpaw Clan** http://cata.cavernoftime.com/quest=26213
**Meet Two-Shoed Lou** http://cata.cavernoftime.com/quest=26215
**Livin' the Life** http://cata.cavernoftime.com/quest=26228
**Lou's Parting Thoughts** http://cata.cavernoftime.com/quest=26232

**Comment by Echinaceax** [comment] 2020-05-04 18:04
conflicting storyline here https://wow.gamepedia.com/Westfall_storyline

i started from 
**Hero's Call: Westfall!**
**Murder Was The Case That They Gave Me**
https://www.wowhead.com/quest=26213/hot-on-the-trail-the-riverpaw-clan

**Comment by Echinaceax** [comment] 2020-05-20 12:12
### more info
Seems that this is messing up the delivery / npc phasing for #145

**Comment by mfranca0009** [comment] 2020-06-28 20:56
Cavern of Time splits the series up depending on what quest you choose.

Murlocs: http://cata.cavernoftime.com/quest=26214
Riverpaw: http://cata.cavernoftime.com/quest=26213

It doesn't change what quests you can pick up later though. Are you suppose to be able to do both or only do one? @Echinaceax

**Comment by Echinaceax** [comment] 2020-06-28 21:47
from what happened @mfranca0009 

i was given https://www.wowhead.com/quest=26213/hot-on-the-trail-the-riverpaw-clan  twice 

![2 of same quest](https://user-images.githubusercontent.com/39439201/85958921-b53c8a80-b999-11ea-9a54-fd91c29b84d8.jpg)

that shouldnt happen :)

**Comment by mfranca0009** [comment] 2020-06-28 22:20
Tested three times and did not recieve a duplicate of "Hot On the Trail: The Riverpaw Clan". storyline / quests were functioning as intended and am unable to reproduce issue.

**Closed as completed by mfranca0009** 2020-06-28 22:20 UTC
Labels: Cannot Reproduce
