### ISSUE TITLE
[quest] Find Fanny

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3436] opened 2019-09-26 20:19 UTC
**Links:**
https://www.wowhead.com/quest=28378/find-fanny
from WoWHead or our Armory
https://www.wowhead.com/quest=28378/find-fanny
**What is happening:**

there is no Fanny

**What should happen:**
there should be a npc to complete q

**Comment by Kitzunu** [comment] 2019-09-26 20:35
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/291

**Closed** 2019-09-26 23:05 UTC
