### ISSUE TITLE
Holy Word: Chastise can Semi-Freeze enemies if they haven't reached melee distance

### ISSUE THREAD

**Issue by Kooler17** [WoWManiaUK/Blackwing-Lair#4301] opened 2020-03-25 17:56 UTC
**Links:**

Spell= holy Word: Chastise http://cata.cavernoftime.com/spell=88625

**What is happening:**

If there is an enemy that is far away, I'll attack it to get it to start aggro towards me, so it can melee attack me while I spell it out. But I have found out that if I hit the enemy with my Holy Word: Chastise spell while it runs towards me, it will stop where it is, and let itself get attacked by anything (I have not tested this with other real players around, just solo battles). No matter what I do the enemy will stay there, only using the ranged ability once every 10 seconds or so approximately. If I move and arrow keys to change directions, they will melee charge me again, but only after I move.

**What should happen:**

Holy Word: Chastise should maybe stun them for a short time, not sure the exact mechanics of it as its my first time playing a character with this spell. But it shouldn't make them semi-freeze indefinitely? And I say semi freeze because they do a ranged attack sometimes lol. 

Let me know if anymore data is needed and feel free to discord me, kooler#9133, I might not check this often if you need anything, discord is the way to go. 

Thanks for any help, this bug actually helps me at times lol but its better for the game to work as it should. :)

**Comment by Echinaceax** [comment] 2020-03-25 17:59
Still needs a spell ID @Kooler17  :)
Thats why we ask for links http://cata.cavernoftime.com/spell=88625

**Comment by mfranca0009** [comment] 2021-02-15 21:19
At the moment, this spell looks fine when I tested it on "Schnottz Air Trooper" in Uldum. This NPC has ranged attack with a gun and uses a bomb spell for ranged spell combat.

https://www.wowhead.com/npc=46979/schnottz-air-trooper

I opened up with Holy Word: Chastise, he gained the debuff and became stunned / disoriented, and then once it expired he was attacking me with his ranged ability and auto-shoot of his gun.

Closing this for now, cause can't reproduce the problem; re-open if the problem comes up again.

**Closed** 2021-02-15 21:20 UTC
Labels: Class/Spells
