### ISSUE TITLE
Human Starter Zone (Paladin)

### ISSUE THREAD

**Issue by Tatoepaladin** [WoWManiaUK/Blackwing-Lair#2541] opened 2019-06-23 21:13 UTC
**What is happening:**
You get to the quest for your class. But it still says you are in need of learning Judgement skill from the trainer.

**What should happen:**
Quest should recognize that the skill has been learned before/after accepting the quest.

**Comment by sarahkay88** [comment] 2019-06-24 06:40
#669 I'll. Reopen the old report now.

**Comment by Echinaceax** [comment] 2019-06-25 06:45
@Kitzunu this is a duplicate of #842
angel referenced hers because bagi had added his newest info to that report.
still a duplicate

**Closed by Echinaceax** 2019-06-25 06:45 UTC

**Comment by sarahkay88** [comment] 2019-06-25 06:58
#669 human quest #842 dwarf quest
