### ISSUE TITLE
[Quest] Corrupting Influence? (Ally) - Can not accept quest as Worgen - Ashenvale

### ISSUE THREAD

**Issue by ssmilazzo** [WoWManiaUK/Blackwing-Lair#5269] opened 2021-07-05 13:28 UTC
**Links:**
https://www.wowhead.com/quest=13868/corrupting-influence
https://www.wowhead.com/item=46128/troll-charm

**What is happening:**
Can not accept quest as a worgen

**What should happen:**
I should be offered quest
![Screenshot (16)](https://user-images.githubusercontent.com/25713425/124478501-40055180-dd73-11eb-8cd2-aa0fdf4e403d.png)

**Is it crashing the server?:**
No
**Other Information:**

**Comment by ssmilazzo** [comment] 2021-07-05 13:32
Passed issues with this quest/item:

https://github.com/WoWManiaUK/Blackwing-Lair/issues/4685
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2118

**Comment by Echinaceax** [comment] 2021-07-05 13:37
I remember a few issues with this one @ssmilazzo 

thanks for reporting this issue because i Tested this and nightelf was fine https://github.com/WoWManiaUK/Blackwing-Lair/issues/4685#issuecomment-774774035

**update**

yes Worgens should get https://www.wowhead.com/item=46128/troll-charm same as all other Alliance races

https://www.youtube.com/watch?v=HgE-eSsFQYQ

**Comment by Echinaceax** [comment] 2021-07-05 13:50
@mfranca0009 

test one confirmed bug for worgen

![image](https://user-images.githubusercontent.com/39439201/124480567-b02dca80-dda7-11eb-8cf4-9c46b50523b8.png)

worgens need adding to the race allowance :)

**notes, Races tested so far**

- [x] Nightelf 
- [x] Human

**Comment by mfranca0009** [comment] 2021-07-05 16:36
All set 👍 

I've also fixed MANY other quests only being offered to Alliance that was excluding Worgens as well.

**Comment by Echinaceax** [comment] 2021-07-05 16:44
comfirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/124500791-ac5a7200-ddc0-11eb-828a-c2903206013b.png)
![image](https://user-images.githubusercontent.com/39439201/124501003-0d824580-ddc1-11eb-93a8-84a76dcf9698.png)


**extra info** 

Next quest is offered too :)

![image](https://user-images.githubusercontent.com/39439201/124501160-5934ef00-ddc1-11eb-9276-6718011f3619.png)

**Closed as completed** 2021-07-24 08:01 UTC
Labels: Fixed in Dev - Confirmed by tester
