### ISSUE TITLE
[Quest] The Storm King's Vengeance - ID 12919

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2424] opened 2019-06-17 11:23 UTC
**Links:** [Quest] https://www.wowhead.com/quest=12919/the-storm-kings-vengeance

**What is happening:**

It is possible to talk to Gymer to get on his shoulders
It is possible to use 3rd spell (grab ennemy or storm)
It is possible to use 4th spell (throw ennemy or storm)

I'm unable to fulfil my quest. Slaying ghouls (i.e) doesn't complete the quest.
I'm unable to regen my energy nor my health by using storms

**What should happen:**

Slaying scourge's army should count on quest.
Grabbing storms should provide energy to use 1st and 2nd spells in order to continue the quest.

**Comment by Rushor** [comment] 2019-06-17 12:43
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/2382 fix will be on live soon

**Closed by Rushor** 2019-06-17 12:43 UTC
Labels: Duplicate
