### ISSUE TITLE
[Object/Dungeon] Door Blackrock Depths 

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3401] opened 2019-09-24 14:01 UTC
**Links:**
https://imgur.com/BQLykJL
https://imgur.com/SlsMmTi
**What is happening:**
After you kill the first wave in the Ring of Law nothing happens after and you are stuck there.
**What should happen:**
After serveral waves the boss should apper and kill it

**Comment by Rushor** [comment] 2019-09-24 17:00
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/910

**Closed by Rushor** 2019-09-24 17:00 UTC
