### ISSUE TITLE
Worgen Druid texture bug and client crash

### ISSUE THREAD

**Issue by NoraDR** [WoWManiaUK/Blackwing-Lair#3021] opened 2019-08-09 17:28 UTC
Well I got my travel form not long ago and I noticed that if I transform from cat form into travel form and back to cat form I was a different colour:
my actual colour:
![WoWScrnShot_080919_183909](https://user-images.githubusercontent.com/52752615/62796442-8e533c80-bad9-11e9-9ce4-1f7cb47cf249.jpg)
![WoWScrnShot_080919_183918](https://user-images.githubusercontent.com/52752615/62796450-9317f080-bad9-11e9-8356-1b7723bba439.jpg)
what it turns into:
![WoWScrnShot_080919_183934](https://user-images.githubusercontent.com/52752615/62796458-9e6b1c00-bad9-11e9-8dc1-dbc3a50d1e76.jpg)
I then to my horror removed my cat form and found this monstrosity:
![WoWScrnShot_080919_183743](https://user-images.githubusercontent.com/52752615/62796519-c8244300-bad9-11e9-85f0-5d0aec36b412.jpg)
![WoWScrnShot_080919_183948](https://user-images.githubusercontent.com/52752615/62796523-ca869d00-bad9-11e9-8160-16c4021e827d.jpg)
![WoWScrnShot_080919_183953](https://user-images.githubusercontent.com/52752615/62796525-cc506080-bad9-11e9-82d5-4881f4987a21.jpg)
This is not the only one of these if I enter a building in travel form I get this:
![WoWScrnShot_080919_184149](https://user-images.githubusercontent.com/52752615/62796577-e4c07b00-bad9-11e9-8166-251e6d2ce82c.jpg)
![WoWScrnShot_080919_184206](https://user-images.githubusercontent.com/52752615/62796580-e68a3e80-bad9-11e9-8230-0285d8db9a2c.jpg)
![WoWScrnShot_080919_184234](https://user-images.githubusercontent.com/52752615/62796601-e9852f00-bad9-11e9-81e7-e909f3944e94.jpg)
this is not a 1-time thing I can do this consistently in many places I've relogged and relaunched since and it still happens other people can see this too and it happens to my friend this is pretty scary ngl...
![WoWScrnShot_080919_192420](https://user-images.githubusercontent.com/52752615/62797326-b93e9000-badb-11e9-8c5f-10fac5d17bc5.jpg)

**Comment by NoraDR** [comment] 2019-08-10 08:05
I went to the barber trying to change my druid form colour, as both I and my friend both had the same colour and I thought it might be that. I changed it to the black I always turn into when I'm bugged and found that after this happened with the black colour there is no way to get rid of it. Usually I can go back into cat form and Worgen form from cat form and it'll be fixed but not with the black colour, it also crashed my game when I tried to go to the barber and change my colour with the many human faces one, but the other one, when I went into the barber, didn't crash but instead showed me a default male on my human in the corner image, maybe its just female worgens that have this problem?

**Comment by NoraDR** [comment] 2019-08-10 09:12
running wild with the texture bug does this XD
![WoWScrnShot_081019_111054](https://user-images.githubusercontent.com/52752615/62820087-a5d50880-bb5f-11e9-9732-27454392783e.jpg)

**Comment by NoraDR** [comment] 2019-08-10 10:15
Using the mall stone with the bug crashes my game^

**Comment by NoraDR** [comment] 2019-08-10 10:19
![Screenshot (808)](https://user-images.githubusercontent.com/52752615/62820747-0d438600-bb69-11e9-94ff-7651074be187.png)

**Comment by NoraDR** [comment] 2019-08-10 10:23
shows male portrait on female worg
![WoWScrnShot_081019_122256](https://user-images.githubusercontent.com/52752615/62820782-9eb2f800-bb69-11e9-8be1-23e2f05bf6ba.jpg)

**Comment by Echinaceax** [comment] 2019-08-10 10:34
@NoraDR 
Thanks for the updated info here. this isnt only a visual bug if it crashed your client. i will remove the low prio label and get this tested ok 

@Rushor crashes client when they are in the bugged form https://github.com/WoWManiaUK/Blackwing-Lair/issues/3021#issuecomment-520137140

**Comment by NoraDR** [comment] 2019-08-10 10:36
:)

**Comment by Eirolla** [comment] 2019-08-10 17:14
1- normal worgen form
![image](https://user-images.githubusercontent.com/26048748/62824741-f6258800-bbaa-11e9-84bc-513c8f1f432a.png)

2-Travel form
![image](https://user-images.githubusercontent.com/26048748/62824744-fc1b6900-bbaa-11e9-8abf-6adae167ff97.png)

3-Back to worgen form(from travel)
![image](https://user-images.githubusercontent.com/26048748/62824750-02a9e080-bbab-11e9-898f-7ada7a258118.png)
Body visuals are bugged.

4-bear form 
![image](https://user-images.githubusercontent.com/26048748/62824770-24a36300-bbab-11e9-99fc-b865adadf9eb.png)

5-Back to worgen form(from bear)
![image](https://user-images.githubusercontent.com/26048748/62824771-308f2500-bbab-11e9-870e-95e8ad8014a0.png)
interesting combination of art with gnomes and humans.


----Visual Crash Bug----

--Before Log off at capital--

![image](https://user-images.githubusercontent.com/26048748/62824783-4e5c8a00-bbab-11e9-9df4-ecac420de012.png)

--After--

![image](https://user-images.githubusercontent.com/26048748/62824789-60d6c380-bbab-11e9-9681-2e49cf6f6bc6.png)


Bug: Confirmed.

**Comment by Rushor** [comment] 2019-10-23 11:02
@keader can you inspect that since https://github.com/WoWManiaUK/Blackwing-Lair/issues/3033 was also fixed?

**Comment by Keader** [comment] 2019-10-25 12:49
Because there was a spell issue.
Here is a clientside issue, nothing that i can do.

**Comment by NoraDR** [comment] 2019-10-25 13:06
@keader but other people can see it?

**Comment by Keader** [comment] 2019-10-25 13:18
yes, because all people has same wrong mpq texture 💃 
it should not happens if you use a original 4.3.4 client (without any edits)

**Comment by sarahkay88** [comment] 2019-11-23 20:41
not sure if this help but I just requested a race change for this reason. my worgen hunter go this effect when going in throne of tides.. then when I used two forms to try unbug myself the whole group got a crit error. a GM then un-bugged me, I queued rdf and got the same dungeon and bug appeared again. maybe it as something to do with worgen and throne of tides.
I have correct client and all is upto date

**Comment by Echinaceax** [comment] 2020-04-19 18:53
fixed here #4325
closing this

**Comment by Echinaceax** [comment] 2020-04-19 19:23
reopening because its 2 different issues

**Comment by Echinaceax** [comment] 2020-05-01 04:44
### update 

https://gyazo.com/941d18017c770af0f7e9b2b68a6a22e5

I level a worgen druid female today from 1 - 17 
no graffic issues at all

**Closed** 2020-05-01 04:45 UTC
Labels: Confirmed By Tester, Priority-High
