### ISSUE TITLE
[Quest] Lost in the Floods - Durotar

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1532] opened 2019-04-19 14:15 UTC
**Links:**
QUEST - https://www.wowhead.com/quest=25187/lost-in-the-floods
ITEM - https://www.wowhead.com/item=52514/thonks-spyglass

**What is happening:**
When in the perfect position to trigger the event/cinematic, it says "Requires top of Razor Hill Watchtower"

![WoWScrnShot_041919_161359](https://user-images.githubusercontent.com/44828921/56428020-3ee4c880-62be-11e9-9631-0dfe2ad95d86.jpg)

**What should happen:**
Should trigger a quick cinematic that shows you the location of the NPC that you need to spot.

https://www.youtube.com/watch?v=UYqA0fVL1ns

**Comment by Kitzunu** [comment] 2019-04-19 14:26
Duplicate of #181

**Closed by Kitzunu** 2019-04-19 14:26 UTC

**Comment by DiomacheTharghan** [comment] 2019-04-19 14:38
Ouch sorry
