### ISSUE TITLE
Keepers of Time Reputation Vendor Missing Items

### ISSUE THREAD

**Issue by Novaveteran** [WoWManiaUK/Blackwing-Lair#5071] opened 2021-02-10 16:13 UTC
Links:

https://www.cavernoftime.com/npc=21643
Is the same as on other wikis etc.

What is happening:

The vendor is missing a bunch of class specific items.

What should happen:

It should have the class specific lvl 70 items.

Is it crashing the server?:

No.

Other Information:

**Comment by mfranca0009** [comment] 2021-02-12 18:48
All set 👍 

Only item missing is "Key of Time" (30635) because it was removed in Cataclysm expansion (at or before patch 4.2.0).

**Comment by Echinaceax** [comment] 2021-02-12 20:49
confirmed fixed in PTR 
some items are not seen coz of class specific
though seemd priests see all :P

**Closed as completed** 2021-02-24 14:04 UTC
Labels: Fixed in Dev - Ready to test, Fixed in Dev - Confirmed by tester
