### ISSUE TITLE
accessing the molten front Quest hub

### ISSUE THREAD

**Issue by z1179** [WoWManiaUK/Blackwing-Lair#1750] opened 2019-05-06 09:40 UTC
**Links:**
https://www.wowhead.com/guide=58/a-guide-to-the-molten-front-and-respective-quests
from WoWHead or our Armory

**What is happening:**
Honestly there is so much involved in this particular Patch( like 4.2.0 or 4.1.0 i believe)
that mentioning it all would take more time than i am willing to invest, but the Molten Front is a level 85 questing hub in cata meant to gear out players before the firelands raids, was  just wondering if we could get a portal teleporting us to this area (the portal should be located at the Gates of sothann to the right of the sulfuron spire in hyjal)

**What should happen:**
Should happen would involve the entirety of Hyjal being fixed to almost 100% working order for all the phasing to work in its entirety, but i dont believe this is a feasible option, especially with the number of 85s growing daily, possibly just put a portal to the zone an fix whatever  prerequisites are involved  to unlock the quests in that hub.

**Comment by Kitzunu** [comment] 2019-05-06 10:29
This might be me misunderstanding this post, but what is the issue here?

From what I can tell this is a suggestion and not an issue, I believe Hyjal has been reported, if I am wrong and you find bugs please feel free to do so. 

We cannot fix something if not the information is there, as I said I might be misunderstanding this, but I cannot see what is wrong except the Hyjal quest chain which is reported (?)

**Comment by z1179** [comment] 2019-05-06 10:31
Once the hyjal quest chain is completed, at 85 you get a seperate quest chain that takes you back to hyjal in order to take on the challenges of the molten front, as far as it goes from a questing point they are considered 2 seperate questchains, one being hyjals 80-82 quest chain, the other being molten fronts 85 only quest chain, it would be considered a seperate entity from the hyjal quest issue which would be isolated to the leveling up aspect

**Comment by Echinaceax** [comment] 2019-05-06 11:18
@Kitzunu - i told them to make this report at they was posting this problem in Discord.

from what i believe and understood from this is now that people on the server have hit 85 they want to progress to do their stuff. thats why their here.

Hyjal being broken is a huge issue for lvling after 80 and progression too as we all know, though this issue isnt intirely "game breaking" while lvling. it definately is when you hit 85 (coz of broken zone)

tagging this pending for now 

@z1179 - thank you for take the time to add info i asked you too do

**Comment by Kitzunu** [comment] 2019-05-09 07:53
To me, this looks like a suggestion and not a bug report.

GitHub is for issues only, any suggestions please take them for the forum.

The 2 dungeons should be completed soon which would give everyone a start to the endgame content, if you are unable to access those dungeons because of the hyjal quest chain, that is another discussion.

Read more here. https://wow-reign.com/news/view?id=4

I will close this issue, Reason: Suggestion, not a bug report.

**Closed by Kitzunu** 2019-05-09 07:53 UTC
Labels: Pending

**Comment by z1179** [comment] 2019-05-09 10:10
since this is most def. a valid bug, it is not  part of the Hyjal questchain, it came a few patches later when firelands was a released. i will no longer be making any bug reports if they are just going to be viewed as invalid

**Comment by Kitzunu** [comment] 2019-05-09 10:32
To me this looks like it is a suggestion to add a portal to the quest hub.

If there is another bug that is not reported, please tell me. But I cannot see the bug reported here if there is any

**Comment by z1179** [comment] 2019-05-09 13:46
While yes that suggestion is in there, the problem as a whole and the entire reason for this report is that the quests to unlock the hub are bugged

**Comment by Echinaceax** [comment] 2019-05-09 15:06
> the problem as a whole and the entire reason for this report is that the quests to unlock the hub are bugged

Exactly, and thats how i read this report too, its not players fault that zones are bugged.
YES suggestion are not for "here" granded BUT... the report was made to "shine a light on other issues in that zone that stops progression. 

@Kitzunu 

> If there is another bug that is not reported, please tell me. But I cannot see the bug reported here if there is any

They all are reported (only need to type in "hyjal" thats how we all know :)
