### ISSUE TITLE
[Quest/Object] Hero's Call Board - All Major Cities

### ISSUE THREAD

**Issue by iTz-AddriX** [WoWManiaUK/Blackwing-Lair#4331] opened 2020-04-02 18:13 UTC
### Hero's Call: Redridge mountains

**Links:** https://www.wowhead.com/object=206111/heros-call-board
NPC https://cata-twinhead.twinstar.cz/?npc=821

**What is happening:** The [Hero's Call Board](https://www.wowhead.com/object=206111/heros-call-board) shouldn't be giving you a repeat quest. 1st one I got in Westfall, 2nd is from Board.

**What should happen:** It should not give you another Hero's Call Request if you already have it at the same location given in the quest area before you leave to go to next area for more questing. 

**Proof:** 
![Capture](https://user-images.githubusercontent.com/62844627/78283847-727b2b80-74ec-11ea-858a-86092a831782.PNG)
![Capture 2](https://user-images.githubusercontent.com/62844627/78283865-79a23980-74ec-11ea-9605-a8cc8e04090d.PNG)

**Comment by Echinaceax** [comment] 2020-04-02 18:18
i think this is an addon issue @iTz-AddriX 
because i have leveled 4 Allies without any issues

disable addons - delete cache then re check

**Comment by iTz-AddriX** [comment] 2020-04-02 18:23
@Echinaceax I got the first one in Westfall, and the 2nd one I got from Hero's Call Board. Same quest and I can turn both in for same reward.

**Comment by Echinaceax** [comment] 2020-04-02 18:27
can you show me ? the westfall one?
logging on

**Comment by iTz-AddriX** [comment] 2020-04-02 18:38
@Echinaceax I completed them both, but it was a guy in Sentinel Hill in Tower there.

**Comment by Echinaceax** [comment] 2020-04-02 18:48
### test confirmed 

https://wow.gamepedia.com/Captain_Danuvin
Yes ive found him thanks :)

![hero and npc](https://user-images.githubusercontent.com/39439201/78290124-84c48c00-7523-11ea-8c2d-67406b504ce7.jpg)


**checked on live**
correct so issue is that if you have taken the quest from **captain danuvin** in Sentinel Hill
the same quest shouldnt be available from the heros board, enabling 2 quest rewards 

**Confirmed on dev** 

![same on dev](https://user-images.githubusercontent.com/39439201/78290760-880c4780-7524-11ea-851f-419383a1a653.jpg)

**Comment by Echinaceax** [comment] 2020-04-02 19:50
### Hero's call: Duskwood 

Note even after delivering the one given from npcs, the hero boards in cities still give it to you, the system need to not give again once a player has 

1. Picked up the quest
2. Not offer same quest from Hero boards and vice versa one the **Hero call** has been answered and delivered

https://www.wowhead.com/npc=900/bailiff-conacher

![same for duskwood](https://user-images.githubusercontent.com/39439201/78295128-e557c700-752b-11ea-95bd-5d0a95371a72.jpg)

**Comment by mfranca0009** [comment] 2020-07-08 18:19
### Hero's Call : Westfall!

Duplicate quests given with different quest descriptions in log

![duplicateWestfall](https://user-images.githubusercontent.com/26092980/86955674-f6653500-c125-11ea-911c-9da25bb5490f.png)

**Comment by mfranca0009** [comment] 2021-07-07 18:08
Westfall and Duskwood opening quests should now be all set and can only be picked up once, not both.

**Comment by Echinaceax** [comment] 2021-07-07 18:41
confirmed fixed in ptr

**Closed** 2021-07-24 08:01 UTC
Labels: Fixed in Dev - Confirmed by tester
