### ISSUE TITLE
[NPC] Zulian Gnasher (spell cast) - Zul'Gurub

### ISSUE THREAD

**Issue by Thelonnious** [WoWManiaUK/Blackwing-Lair#4659] opened 2020-08-11 22:23 UTC
**Links:**

https://www.wowhead.com/npc=52413/zulian-gnasher

**What is happening:**

dont cast spells 

**What should happen:**
need to cast spells
**Is it crashing the server?:**
no

**Other Information:**

**Comment by Echinaceax** [comment] 2020-08-13 19:46
@Xman993 
What spells these 2 https://www.wowhead.com/npc=52413/zulian-gnasher#abilities:0+1+17+2 ?

**Comment by Thelonnious** [comment] 2020-08-13 19:49
yes @Echinaceax

**Comment by Echinaceax** [comment] 2020-08-13 19:50
Confirmed fixed in dev 

![spells](https://user-images.githubusercontent.com/39439201/90180244-fa344900-ddae-11ea-8d65-580c89cccc2e.jpg)

**Comment by Echinaceax** [comment] 2020-08-18 12:40
Due to PTR wipe this reverted too

**Comment by mfranca0009** [comment] 2021-01-28 18:29
SmartAI needs to be done on heroic NPC, it is currently on the normal NPC.

**Closed as completed** 2021-01-30 11:28 UTC
Labels: Fixed in Dev - Ready to test, Fixed in Dev - Confirmed by tester, Dungeon/Raid
