### ISSUE TITLE
[Spell]  Vanish

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2057] opened 2019-05-26 20:11 UTC
**Links:**

https://cata-twinhead.twinstar.cz/?spell=1856
link to vanish spell

**What is happening:**

https://youtu.be/FpoNKlMqEsw     -   video showing that vanish isnt dropping combat and the mob doesnt even flinch and keeps attacking you

**What should happen:**

vanish should be dropping you out of combat and the mobs should then all reset

**Comment by Denrunmt** [comment] 2019-08-06 16:16
Saw that there has been an issue already opened about that. It's closed but the problem still persists. Vanish works only if you haven't attacked the mobs , get away from them by like 10-20 yards and cast it. If I'm attacking the mobs and try to vanish while they are in my body and are attacking me the spell just doesn't work. I'm still in combat and none of the mobs stop the attacks.

**Comment by Xman993** [comment] 2019-09-16 08:49
i still have the problem on dev. vanish does not drop the combat, you instantly get out of stealth and does not reset the mobs

Vanish
- Allows you to vanish from sight, entering stealth while in combat. For the first 3 sec after vanishing, damage and harmful effects received will not break stealth. Also breaks movement impairing effects.

**Comment by Echinaceax** [comment] 2019-09-16 09:16
@Xman993 same on live ?

**Comment by Xman993** [comment] 2019-09-16 09:27
@Echinaceax  i dont have a rogue on live :D

**Comment by Randomplayerx** [comment] 2019-10-01 13:19
Problem still exist.
Vanishing vs NPCs [PVE] is not breaking casting, mob is keeps the aggro on you to target you.

**Comment by Druhl** [comment] 2019-10-21 23:34
Confirmed, neither Vanish nor Shadowmeld racial work right on my rogue. Mobs ignore it.

**Comment by Rushor** [comment] 2019-10-23 16:35
any more info on that?

**Comment by Hespericless** [comment] 2020-02-29 02:47
Apparently, as you're not getting the 3 second improved stealth, the mobs just keep attacking you because it's the same as if you step way too near a mob on normal stealth, they detect you, attack you and then you break stealth.
Hope this helps

**Comment by mfranca0009** [comment] 2021-02-01 00:55
**Update:**

As of right now, every time I cast Vanish while STANDING STILL the NPCs attacking me will reset. If I were to run away while casting vanish, it doesn't register and they continue to attack me.

**Comment by mfranca0009** [comment] 2021-02-01 05:14
Should be fixed.

- [x]  Vanish `Improved Stealth` aura now shows up for 3 seconds.
- [x] While having the vanish aura, it should not break when receiving damage (from debuffs applied by an NPC)
- [x] NPCs should not continue attacking you when vanishing.
- [x] After vanish aura has expired, it transitions into normal stealth; damage can break stealth at this point.

**Comment by HrafnValknutt** [comment] 2021-02-01 09:47
Fixed in Dev confirmed

**Closed** 2021-02-11 11:11 UTC
Labels: Class/Spells, Confirmed By Tester, Fixed Confirmed, Fixed in Dev
