### ISSUE TITLE
Priority high? Resurrection bug

### ISSUE THREAD

**Issue by dagget1337** [WoWManiaUK/Blackwing-Lair#4512] opened 2020-05-18 00:55 UTC
**What is happening:**

Seems no1 wrote anything about this bug or i´m too dumb to find it here.
So when in a group and one party member (or not even in grp) dies (in a dungeon or outside) and releases his body, he cant get resurrected.

**What should happen:**

When someone leaves his body upon death, he should be able to get resurrected when clicking any kind of Resurrectionsspell and on the soulless body.

**Other Information:**
Since the dungeon Blackwing Decent is between 2 zones where only one has a Flightmount as Ghost and one not (Burning steppes doesnt have and Searing Gorge does have a Griphon mount)
its annoying for the most time whenever there is a Raid wipe and one who doesnt know the way inside releases his corpse, just to get dismounted and stuck outside as ghost until he figures out how to get inside.

**Comment by mfranca0009** [comment] 2021-02-09 03:37
Definitely need more information here, need to know the spell or spells that was trying to be used and then I'll be able to look for any issues specific to the problematic spells. @Echinaceax 

Currently, the resurrection effects that are coded look fine, and should work.

**Comment by Echinaceax** [comment] 2021-02-09 09:51
ah i think i understand what he means @mfranca0009 

**_releases his body, he cant get resurrected._**

If a player releases and goes to the graveyard the body becomes none resurrected by a healer or a mass summon guild perk,   
 (Blizzlike as far as i remember)

**_Since the dungeon Blackwing Decent is between 2 zones where only one has a Flightmount as Ghost and one not (Burning steppes doesnt have and Searing Gorge does have a Griphon mount)
its annoying for the most time whenever there is a Raid wipe and one who doesnt know the way inside releases his corpse, just to get dismounted and stuck outside as ghost until he figures out how to get inside._**

player wants you to make it easier for them to get back into BWD raid when they wipe @mfranca0009 

Advice
1. Try not to wipe
2. if you do wipe, tell the raid NOT to release, then only one of the players with resurrection spell/perk needs to fly to that crappy zone to rez the rest of the players
3. When your at graveyard, go the correct way when you come out of the building and you will have a spirit mount, you only lose the mount if you go the wrong way or fall off your mount

**Comment by golosomie** [comment] 2021-02-09 13:06
> If a player releases and goes to the graveyard the body becomes none resurrected by a healer or a mass summon guild perk,
> (Blizzlike as far as i remember)

@Echinaceax 
Can you get any confirmation on the last part? In WotLK you could resurrect people that released their spirit.

**Comment by Echinaceax** [comment] 2021-02-09 13:17
> @Echinaceax
> Can you get any confirmation on the last part? In WotLK you could resurrect people that released their spirit.

Sometimes its hard to find the 100% info as you know
I will ofc reseach this but Reporters are actually meant to provide the proof not the testers @golosomie 
then we reopen and look into it

**Comment by golosomie** [comment] 2021-02-09 13:48
@Echinaceax 
[Resurrect on wowpedia](https://wow.gamepedia.com/Resurrect#Tips)

> There are some common misconceptions involving resurrection and releasing. Players can be resurrected whether or not they release. [...]
> If they have released and the body is out of range, the resurrector must click the spell and mouse over the corpse since the corpse is not selectable.

So the report is correct.

**Comment by Echinaceax** [comment] 2021-02-09 13:54
@mfranca0009 
 Seems correct as @golosomie linked 

![image](https://user-images.githubusercontent.com/39439201/107373245-9b922280-6ae6-11eb-8bb6-6d947d122326.png)


thanks for the research @golosomie 👍

**Comment by mfranca0009** [comment] 2021-02-10 00:33
All resurrections now work even if they have already released their spirit, including mass resurrection from guild perks.

**Comment by Echinaceax** [comment] 2021-02-10 01:00
confirmed fixed in PTR

**Closed as completed** 2021-02-11 11:10 UTC
Labels: Fixed in Dev - Ready to test, Fixed in Dev - Confirmed by tester, Confirmed By Tester, Class/Spells
