### ISSUE TITLE
[QUEST] Ambushed!

### ISSUE THREAD

**Issue by fllo55555** [WoWManiaUK/Blackwing-Lair#3405] opened 2019-09-24 18:44 UTC
**Links:**
https://www.wowhead.com/quest=27171/ambushed
from WoWHead or our Armory

**What is happening:**

Mobs are missing

**What should happen:**

Mobs should be spawned into the grave with drop of quest items

**Comment by Rushor** [comment] 2019-09-24 19:00
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/373

pls check the github https://github.com/WoWManiaUK/Blackwing-Lair/search?q=search&unscoped_q=search in the repo before posting new bugs thanks @fllo55555

**Closed by Rushor** 2019-09-24 19:00 UTC
