### ISSUE TITLE
[Talent/Warlock/] Bane of Havoc - not working

### ISSUE THREAD

**Issue by marcwr1** [WoWManiaUK/Blackwing-Lair#2298] opened 2019-06-07 19:19 UTC
**Links:**

http://cata-shoot.tauri.hu/?spell=80240

**What is happening:**

Doesn't do any Damage to the baned target, when dealing dmg to another target.

**What should happen:**

It should cause 15% of all damage done to other targets to also be dealt to the baned target.

**Comment by Dranah** [comment] 2019-06-23 19:27
Something went sideways here. The damage transferred is too high and makes no sense.

TEST:
Soul fire hitting main target for 20k crit, Bane on other target transfers 5k damage instead of 3k (which would be 15%)
Then Burning embers begin ticking on main target for 1k damage, the Bane target is receiving 2,4k damage ticks off it. That's about 240% of it. 
How it works atm: Transfers too much damage and interacts weird with Burning embers.
How it should work: should transfer 15% of any damage, including that of Burning embers.

**Comment by Keader** [comment] 2019-06-24 19:22
To return exactly 15%, it should not take any modifier.
It should or not get mod?
I'm sending to server to not get any mod, it will always match with 15% now.

**Comment by Itsshupz** [comment] 2021-01-09 21:18
This isnt working atm. Just tested it out and it didnt work.

**Comment by Echinaceax** [comment] 2021-01-09 22:26
please explain in what way @Itsshupz keader will need details

**Comment by Itsshupz** [comment] 2021-01-10 10:52
So, **The Bane of Havoc** is a Spell that Banes the target for 5 min, causing 15% of all damage done by the warlock to other targets to also be dealt to the baned targets. So for instance I have 2 targets and 1 target should have the bane and I hit the first target with 10000, the other target who is baned should receive 1500 damage. This is not working because the targed who has the bane isnt getting damaged

Hopefully this is good explaned

Goodluck

**Comment by Echinaceax** [comment] 2021-01-10 10:54
@Keader can you take another look at this please

orig fix was for 
_How it works atm: Transfers too much damage and interacts weird with Burning embers._

now seems something not right

**Comment by mfranca0009** [comment] 2021-02-12 02:14
All set 👍 will now cause 15% of all damage done from other target(s) to the one afflicted with Bane of Havoc.

**Comment by golosomie** [comment] 2021-02-14 01:19
@mfranca0009 Confirmed fixed on PTR. Works across multiple targets, damage seems fine.

**Closed** 2021-02-24 14:04 UTC
Labels: Class/Spells, Fixed Confirmed, Fixed in Dev, Regression

**Comment by Schoxxy** [comment] 2021-04-25 12:54
Bane of Havoc Crashes the server when used inside of Castle Shadowfang.

**Comment by Echinaceax** [comment] 2021-04-25 13:16
![image](https://user-images.githubusercontent.com/39439201/115994908-3b852580-a5d9-11eb-9f6d-4dc3ddfde796.png)

@mfranca0009 
Seems the fix has caused server to crash inside dungeon

**Comment by golosomie** [comment] 2021-04-26 22:16
@Echinaceax I couldn't reproduce the server crashing in Shadowfang Keep hc.
Need info if it happened on any specific mob / spell

**Comment by Schoxxy** [comment] 2021-04-27 06:58
https://ibb.co/vscHp16

The Blue one Marked was the adds where I used the spell 3 Times on the ghost adds,  and it crashed afterwords.
The red one II used on the bossfight on a Add that the boss spawns.
I was in a groub with 2 Paladins (Heal,Tank), Schadow priest, Survival hunter.

**Comment by Echinaceax** [comment] 2021-04-27 07:08
Thanks @Schoxxy 

Drache - we might have to try an reproduce with Schoxxy on live and see if it crashes again if you cant on PTR
