### ISSUE TITLE
[Spell] Entangling Roots (PvP Issue) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4346] opened 2020-04-05 05:03 UTC
**Links:**

http://cata.cavernoftime.com/spell=339

**What is happen**
- In PVP duration is only 6 secs instead of up to 30

**What should happen:**
_Duration needs increasing 30 in pvp too_

reported to me by Nub

**Comment by Kadajj** [comment] 2020-04-13 07:47
I know on the 4.0.6. patch the Entangling Roots have a duration of 8 seconds not 30. not sure on 4.0.3

**Comment by Echinaceax** [comment] 2020-04-13 08:05
Yes this was reported to me by a player, the thing is with this (pvp) side issue its at constant 6secs no matter if its the very 1st cast on target or or 5th its always 6secs

so as a previous comment regarding  Diminishing returns https://wow.gamepedia.com/Diminishing_returns  stated that it should deminish too the more times its cast, So also tested (always 6s) never lower or immune, so something is wrong. 

@Kadajj im good with the 8esc (patch 4.0.6) thanks for update
then it still needs looking at for the 6s too 8s and ( Diminishing returns/ immune)

**Comment by mfranca0009** [comment] 2021-02-09 06:17
@Echinaceax 

Currently this is working as intended, in PvP it will have the following durations:

**First cast on same target:** 8 seconds
**Second cast on same target:** 3 seconds
**Third cast on same target:** 1 or 2 seconds

This is a WoWhead comment, from patch 5.0.4, but it says:
_"In PvP, it seems to work first for about seven seconds, then three, then one, then none with roughly five seconds before it'll work again."_

**Also, in patch notes for diminishing return effect:**

Patch 1.7.0 (2005-09-13): Entangling Roots now shares the same duration in pvp as other long-duration forms of crowd control (ie: polymorph, fear, sap).
Patch 1.4.0 (2005-04-19): Now subject to diminishing returns in PvP. This is considered an immobilizing effect.

**Recent patch notes related to Cataclysm:**

Patch 4.2.0 (2011-06-28): Entangling Roots and the equivalent spell triggered by  [Nature's Grasp] no longer deal damage.
Patch 4.0.6 (2011-02-08): Now has a PvP duration of 8 seconds.

At the moment, working as intended so closing issue 👍

**Closed by mfranca0009** 2021-02-09 06:17 UTC
Labels: Invalid
