### ISSUE TITLE
[Quest] The Fighting Spirit - ID 27810 - Twilight

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#282] opened 2018-12-22 14:14 UTC
Quest - https://www.wowhead.com/quest=27810/the-fighting-spirit
NPC - https://www.wowhead.com/npc=46811
can speak with the required NPC - https://www.wowhead.com/npc=46813/mullan-gryphon-rider but cannot challenge them.

**Comment by Rushor** [comment] 2019-08-01 12:00
https://i.imgur.com/WzFtbDS.jpg spamms the chat. will fix that

**Comment by Rushor** [comment] 2019-08-01 12:24
okay you can fix pls

**Comment by Rushor** [comment] 2019-08-01 12:33
if you check it in UpdateVictim it will spamm because it will be checked every 50 ms, there must be another check

**Comment by Bathelmo** [comment] 2019-08-01 13:27
no it won't

**Comment by Bathelmo** [comment] 2019-08-01 13:28
this script is a one on one replicate of chapter1.cpp dk_initiate, dunno what you on about m8

**Comment by Bathelmo** [comment] 2019-08-01 13:32
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp

npc_death_knight_initiate();

**Comment by Echinaceax** [comment] 2019-08-03 16:50
can challange him now 

![fixed1](https://user-images.githubusercontent.com/39439201/62414712-8863e400-b61f-11e9-896a-62f9f1329531.jpg)

**Comment by Druhl** [comment] 2020-01-13 22:18
Still an issue.

**What should happen:**
NPC offers duel dialog, duels, loses to player, player gets credit.

**What does happen:**
Did this twice (see chat log in 2nd screenshot), never get credit for successful defeat of quest NPC. Cannot complete quest.

![WoWScrnShot_011320_171442](https://user-images.githubusercontent.com/19803911/72296753-6176f880-3628-11ea-9b26-b43c7331cfd0.jpg)

![WoWScrnShot_011320_171644](https://user-images.githubusercontent.com/19803911/72296805-83707b00-3628-11ea-84fd-dbab7422ebba.jpg)

**Comment by Echinaceax** [comment] 2020-01-17 09:12
Confirmed on live 
Something broken again and dialog still spams chat (seeing as Bathelmo is no longer here)
@Rushor can you take a look please 

tested in dev
cant complete the duel
Holy crap this wasnt like this before (whopper chat spam too)

![spam](https://user-images.githubusercontent.com/39439201/102320724-fdb62780-3f7c-11eb-9945-39c659e623a3.jpg)





Thank you @Druhl

**Comment by mfranca0009** [comment] 2020-07-07 19:48
This still an issue? Works right now on PTR.

No chat spam, NPC says opening line and closing line, gives quest completion.

**Comment by Echinaceax** [comment] 2020-07-07 20:52
my last check was on dev in january @mfranca0009 
we have had a new client since then so havent checked 

I ask GM to check 
yes spam is still there on live @mfranca0009 

after challanging the mullan gryphon rider, the spam happens

![yes same](https://user-images.githubusercontent.com/39439201/86842445-7dbe9400-c0a5-11ea-88e3-34bcd4dd48a5.jpg)

**Comment by mfranca0009** [comment] 2020-07-14 19:51
Looking into this further, seems the NPC needed for the quest is ran by C++ script and not entirely smart script in DB. While the quest works on PTR, will need to adjust the C++ script because it's saying a duplicate line, "DEFINENTLY" is misspelled, and it should display a duel countdown for when the duel starts. Apparently from the quest video on WoWhead the NPC is suppose to despawn after dueling him/her as well.

https://www.wowhead.com/quest=27810/the-fighting-spirit#videos:id=88639

**Comment by mfranca0009** [comment] 2020-12-16 02:58
Eliminated the extra talk line where it's repeating "fightin' words!" and also eliminated some parts that weren't needed within the C++ script. Still need to fix the duel countdown. For some reason its not showing up at all even when it's called.

**Comment by mfranca0009** [comment] 2020-12-20 02:26
All set, needs testing in PTR 👍 

Should function properly now when starting the duel, winning the duel, or losing the duel.

**Comment by Echinaceax** [comment] 2020-12-20 10:15
Confirmed fixed in PTR

**Closed** 2020-12-22 11:34 UTC
Labels: Confirmed By Tester, Fixed Confirmed, Fixed in Dev, Regression, zone 80-85 Cata
