### ISSUE TITLE
[Quest]  Pa'Troll - ID 12596- Zul'Drak

### ISSUE THREAD

**Issue by ghost** [WoWManiaUK/Blackwing-Lair#214] opened 2018-12-19 09:48 UTC
Quest - https://www.wowhead.com/quest=12596/patroll
NPC - https://www.wowhead.com/npc=28039
This issue is I have already completed captains Brandon https://www.wowhead.com/npc=28042/captain-brandon quest, however it has not registered the quest completed therefore this quest cannot be completed.

The following quest was the job he asked to be completed https://www.wowhead.com/quest=12564/troll-patrol-something-for-the-pain, which I did but didn't register.
![world of warcraft 19_12_2018 09_41_41](https://user-images.githubusercontent.com/42302580/50212593-48434000-0373-11e9-8308-fea28c016b8f.png)

**Comment by wow-mania** [comment] 2019-05-11 11:39
![image](https://user-images.githubusercontent.com/12248683/57569219-b0a9c100-73e9-11e9-9179-7b97eeb3a3c3.png)


Works fine quest is given by another NPC. Make sure you have requirements.

**Comment by Venom64bit** [comment] 2019-06-05 09:58
The problem is still there. The report was probably not understood.

During the quest Pa'Troll you need to complete a few of quests from the various commander of the Argent Crusade. All works fine except Captain Brandon's Task.

Quest: https://www.wowhead.com/quest=12564/troll-patrol-something-for-the-pain

**Comment by zippoking** [comment] 2019-06-26 18:55
I can confirm that this quest is still bugged: The quest you do for Captain Brandon, does not count towards the main quest Pa'troll.

![Pa'Troll - how it is](https://user-images.githubusercontent.com/18005338/60206723-953d2d00-9854-11e9-816a-248b191e642b.png)

**Comment by Druhl** [comment] 2020-01-02 21:05
Confirmed. Problem remains.

The quest Captain Brandon (https://www.wowhead.com/npc=28042/captain-brandon) starts and finishes (https://www.wowhead.com/quest=12597/something-for-the-pain) is supposed to satisfy one of the quest requirements of "Pa'Troll" (https://www.wowhead.com/quest=12596/patroll) but counter for this doesn't move and Pa'Troll can't be completed.

**Comment by mfranca0009** [comment] 2020-12-14 01:05
Looks as if the spell that should be rewarded on quest turn-in for:
https://www.wowhead.com/quest=12597/something-for-the-pain

Unfortunately the spell doesn't seem to exist in DBC and says it can't be found, so I'll have to do it a different way.

**Comment by mfranca0009** [comment] 2020-12-14 01:40
All fixed, needs testing in PTR 👍 

![image](https://user-images.githubusercontent.com/26092980/102031273-75206700-3d83-11eb-968e-e4f8bcdb99fd.png)

**Comment by Echinaceax** [comment] 2020-12-14 11:23
Fixed in PTR 
https://gyazo.com/a62c728369249c33a9e265c7dea268aa

note only bug i did see was after each task was completed it show quest credit on screen and in quest log but not on Main map, which some of the quest givers didnt have the quest complete (❓ ) over their heads, but click the npc and you can deliver the quests

other than that all working now

**Closed** 2020-12-15 11:36 UTC
Labels: Confirmed By Tester, Fixed Confirmed, Fixed in Dev, Legacy (wotlk)
