### ISSUE TITLE
[Quest] Night Terrors - ID 28170

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2693] opened 2019-07-08 23:06 UTC
**Links:**
https://www.wowhead.com/quest=28170/night-terrors
from WoWHead or our Armory

**What is happening:**
After entering the cave and phasing into spirit realm, you cant cleanse the "shrines", which is achieved by walking towards the bonfires, resulting in getting no quest progress -> cant complete.

**What should happen:**
In spirit realm phase, quest progress should be earned by walking to one of the three bonfires, quest should be completeable.

**Comment by Rushor** [comment] 2019-07-09 08:43
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/1869

**Closed by Rushor** 2019-07-09 08:43 UTC
