### ISSUE TITLE
[Spell] Kill Command - ID 152637 Hunter (Range Issue)

### ISSUE THREAD

**Issue by Drostthehunter** [WoWManiaUK/Blackwing-Lair#1075] opened 2019-03-26 23:01 UTC
_Issues 2_ 

**Links:**
https://www.wowhead.com/spell=152637/kill-command

**What is happening:**
![Screenshot_8](https://user-images.githubusercontent.com/43518434/55038981-cd00c280-5022-11e9-827c-143d1cde88db.png)
The spell at the moment has range issue, as a hunter you can cast the spell no matter of how far the enemy is but your pet should perform special attack once it gets in close range ( 20 yards ), however the pet performs the attack and makes damage to the enemy no matter how far he is from the target as soon as you use the Kill Command..  Atm he can attack the mob from the range the hunter is shooting.

**What should happen:**
The spell Kill Command commands your pet to perform a special attack once it gets in the range of the enemy, wowhead showing that the range of performing attack is 20yards. Means the pet should not be able to damage the enemy from a higher range.

**Comment by Keader** [comment] 2019-04-18 13:39
Fixed.

**Comment by Dranah** [comment] 2019-04-26 21:41
Combat check works but range does not.
The spell needs your pet in combat and targetting the enemy in order to do damage, but it does damage from well above 20 yards.

**Comment by Keader** [comment] 2019-04-29 14:52
I dont get your regression...
Spell can only be casted if pet has victim and pet victim is below 20 yards.

**Comment by Keader** [comment] 2019-04-29 19:11
i did a little improvement on script...
But i cant reproduce any regression here.
Closing.

**Comment by Dranah** [comment] 2019-04-30 19:55
Original report was incorrect. The check range must be 5 yards.
Works as intended now.

**Closed** 2019-05-02 17:42 UTC
Labels: Class, Fixed Confirmed, Fixed in Dev
