### ISSUE TITLE
[NPC] Grot Deathblow Twilight Highlands

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2175] opened 2019-05-31 19:27 UTC
**Links:**
https://www.wowhead.com/npc=49387/grot-deathblow
**What is happening:**
You cannot browse hes goods (http://i63.tinypic.com/solbg1.jpg)
**What should happen:**
You should browse hes goods ^^

**Comment by Kitzunu** [comment] 2019-06-14 20:55
I fixed this one.

duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/2387

**Comment by Kitzunu** [comment] 2019-06-15 16:09
fixed

**Closed** 2019-06-18 10:05 UTC
Labels: Fixed Confirmed, Fixed in Dev, zone 80-85 Cata
