### ISSUE TITLE
[Quest] [Without a Captain or Crew] Q-ID 26427 -Deepholm

### ISSUE THREAD

**Issue by ice-2020** [WoWManiaUK/Blackwing-Lair#4179] opened 2020-01-23 13:32 UTC
**Links:**
-Quest:
https://www.wowhead.com/quest=26427/without-a-captain-or-crew
-Item:
https://www.wowhead.com/item=58806/spool-of-rope
-Video:
https://www.youtube.com/watch?v=2IxxaHapcKM
**What is happening:**
the spool of rope is not in the ship

**What should happen:**
should pick the spool of rope and Bottle of Whiskey and give them to the quest giver

**Comment by Echinaceax** [comment] 2020-03-22 13:49
There is a phasing issue with this ive notice myself over the last few times

GM also confirms there is a phasing issue, Sometimes there in corrent phase for Mor'norokk and because the ship is moving it phases the NPC out, same issue here too 

i will go dev later and get full info for this

**Comment by Echinaceax** [comment] 2020-03-22 14:38
Confirmed some funky crap 

**Reproduce**
1. Add quest
2 go on ship (if you see the spool rope) 

![spool of rope](https://user-images.githubusercontent.com/39439201/77252243-dc751480-6c52-11ea-8819-8c229269660a.jpg)

3. relog and watch the funky stuff happen

https://gyazo.com/8ef45a817d09d54c81f4cf0f87791ff2

**Comment by Echinaceax** [comment] 2020-11-25 12:51
no issue once phased correctly

**Closed** 2020-11-25 12:51 UTC
Labels: Confirmed By Tester, zone 80-85 Cata
