### ISSUE TITLE
[Restoration Druid - Tier 11 Set Bonus] Bloom

### ISSUE THREAD

**Issue by Sevenblade11** [WoWManiaUK/Blackwing-Lair#4300] opened 2020-03-25 15:31 UTC
**Links:**

http://www.cavernoftime.com/spell=90159
https://wow.gamepedia.com/Stormrider%27s_Vestments

**What is happening:**
Currently, the druid's tier set bonus only activates when you cast Lifebloom. Even when Lifebloom is still active, Bloom, the ability from the tier set bonus, still goes away. 

**What should happen:**
If it's by patch 4.0.3, Bloom should still be active when Lifebloom is active. It should not go away within 8 seconds of Lifebloom being cast if Lifebloom is refreshed by Nourish or any other ability.

If it's by patch 4.2.0, which many other servers use, Bloom should be active when Harmony (Druid's mastery) is active, as shown in the links above.

**Comment by Echinaceax** [comment] 2020-03-25 15:50
patch 4.0.3 atm @Sevenblade11

**Comment by Chicozoba** [comment] 2020-03-25 15:52
It's actually supposed to be 4.3 patch on the server. Only the content is 4.0.X

**Comment by Sevenblade11** [comment] 2020-03-25 16:08
Many class abilities are scaled with 4.3.4 patch, I believe.

**Comment by Echinaceax** [comment] 2020-03-25 17:46
@Sevenblade11 im sure keader will know

**Comment by mfranca0009** [comment] 2021-02-15 21:29
I assume this is the Druid T11 4-piece Bonus effect, since 2-piece Bonus effect is not related to Bloom.

Druid T11 4P Bonus Spell: https://www.wowdb.com/spells/90158-item-druid-t11-restoration-4p-bonus

Will look into this 👍

**Comment by mfranca0009** [comment] 2021-02-15 21:39
Can confirm, it should use Patch 4.2.0's effect, when Harmony is active then you also receive the spirit boost from Bloom.

![image](https://user-images.githubusercontent.com/26092980/107995282-58372880-6fac-11eb-9b1e-a8c7ef509f03.png)

**Comment by mfranca0009** [comment] 2021-02-15 23:38
Modified to fit Patch 4.2.0, all set 👍

**Comment by golosomie** [comment] 2021-02-19 23:21
@mfranca0009 Bloom is applied with Healing Touch, Nourish, Regrowth and Swiftmend with a 10sec duration just as Harmony.
So that's working fine.

But I think Bloom's timer should be reset when Harmony is reapplied while both effects are still running. 
Right now, Bloom's duration will not increase if Harmony is reapplied.

**Comment by mfranca0009** [comment] 2021-02-20 00:52
@golosomie Should be all set now 👍

**Comment by golosomie** [comment] 2021-02-20 01:24
@mfranca0009 Confirmed fixed on PTR. Now only removes Bloom when Harmony is removed.

**Closed** 2021-02-24 14:04 UTC
Labels: Class/Spells, Confirmed By Tester, Fixed Confirmed, Fixed in Dev
