### ISSUE TITLE
[Talent/Druid] Predatory Strikes

### ISSUE THREAD

**Issue by gitkulu** [WoWManiaUK/Blackwing-Lair#2146] opened 2019-05-30 20:08 UTC
**Links:**
Talent: https://www.wowhead.com/spell=16974/predatory-swiftness
Buff: https://www.wowhead.com/spell=69369/predatory-swiftness

**What is happening:**
When the Predatory Strikes talent procs the Predator's Swiftness buff, it makes Cyclone and Entangling Roots instant cast, but those spells do not consume the buff. Additionally, it isn't working with Starfire at all.

**What should happen:**
The Predator's Swiftness buff should make Starfire instant cast, and Cyclone/Entangling Roots/Starfire should consume the Predator's Swiftness buff.

**Comment by Echinaceax** [comment] 2020-04-28 12:26
So this buff is continuing the full duration even after Cyclone and Entangling Roots have been used?

note: i have seen this in arena recently , Predatory Strikes does seem bugged (but as i dont know feral) i dont know how this should work) 

https://wowwiki.fandom.com/wiki/Predatory_Swiftness
https://wow.gamepedia.com/Predatory_Swiftness


![pred strickes1](https://user-images.githubusercontent.com/39439201/80488190-3fe31800-895e-11ea-98a4-16eecd600283.jpg)


so if the buff isnt consumed then can more than one spell be used ?

**Comment by mfranca0009** [comment] 2021-02-11 14:11
Starfire isn't considered a Nature spell, it's considered under the spell school mask of Arcane. Therefore, Starfire should NOT be an instant cast and should NOT be free (costing no mana).

Looking into the buff being consumed though, since this is a possible problem.

**Comment by golosomie** [comment] 2021-02-11 23:56
@mfranca0009 
Can confirm that the buff isn't consumed when casting Cyclone / Entangling Roots / Hibernate instantly even though it should be.
All other affected spells (Wrath, Healing Touch, Nourish, Regrowth) remove the buff correctly. 

The set of spells that profit from the buff seems to be correct. Starfire isn't one of them.

Cyclone: Spell 33786
Hibernate: Spell 2637
Entangling Roots: Spell 339 (wow, that's old..)

**Comment by mfranca0009** [comment] 2021-02-12 02:59
All set 👍

**Comment by golosomie** [comment] 2021-02-13 16:29
@mfranca0009 confirmed fixed in your TR. All spells that profit consume the buff correctly.

**Closed** 2021-02-24 14:04 UTC
Labels: Class/Spells, Confirmed By Tester, Fixed Confirmed, Fixed in Dev, Priority-High
