### ISSUE TITLE
Bugged Quest

### ISSUE THREAD

**Issue by Davydov75** [WoWManiaUK/Blackwing-Lair#2188] opened 2019-06-01 14:46 UTC
Through The troll Hole dun work portal into Zul gurub aint showing

**Comment by giles1508** [comment] 2019-06-01 14:51
Please use the template provided matey,  with a link to quest etc,  plus zul gurub isn't meant to be open yet so this won't be open for a good few months yet, as this is a progressive server, meaning that not everything will be open at once,  there is a set plan to the raids and instances opening

**Comment by gitkulu** [comment] 2019-06-01 15:03
https://github.com/WoWManiaUK/Blackwing-Lair/wiki/How-to-Properly-Report-an-Issue

**Comment by Kitzunu** [comment] 2019-06-01 15:16
Duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/1706

**Closed by Kitzunu** 2019-06-01 15:16 UTC
