### ISSUE TITLE
[Dungeon/Currency] All cataclysm normal dungeons 

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2450] opened 2019-06-18 14:39 UTC
**Links:**

**What is happening:**

Bosses and completing dungeon in normal mode don't award justice points.

**What should happen:**

All bosses from cataclysm dungeons should award 30 justice points on normal mode and completing the dungeon another 140 justice points.

**Comment by fvicaria** [comment] 2019-06-18 15:30
As-is for now.

**Comment by giles1508** [comment] 2019-06-18 22:59
this needs to change from as-is to be honest,  to some players this is thier ownly way to get into heroics,  the crafted pvp gear is getting reduced,  there isnt any other ways for crafted gear as its too low,   and the item  levels from the limited normals we have open is too low to build enough to get into heroics,   this needs to change,   the justice point vendor is now fixed and people need to buy items,  thats literally the whole point of playing normals,  otherwise theres really no point

**Comment by Kitzunu** [comment] 2019-06-18 23:15
You do get JP upon ending the RDF, however it doesnt show in the chat for some weird reason.
¨
As for all normal dungeons bosses dont give JP you need to open sepeare reports as it is too broad

**Comment by giles1508** [comment] 2019-06-18 23:16
confirmed on dev they indeed give jpp for finishing as kitz stated

**Comment by giles1508** [comment] 2019-06-18 23:58
ok tested this tonight with kitz,  several dungeons and research completed,  normal bosses as far as i can see and kitz from all the searching we have done,  they dont yeild any JP at all,   the only JP is from completing the instance,  which as kitz said its fixed,  but it just doesnt show,   check currency table after completing random queue finder to confirm

**Comment by Dranah** [comment] 2019-06-20 02:44
Someone did something on this.
Deadmines at lvl 20 grants JP again... REVERT that asap.
Then again, the report seems valid for dungeons that are lvl 85 on normal difficulty as well.

So Halls of Origination, Grim Batol and Lost City of the Tol'vir (3 dungeons that are not yet open) must award 30 jp per boss on normal too.
Everything else SHOULD NOT GIVE JP ON NORMAL.

**Comment by Rushor** [comment] 2019-06-20 08:38
dm fixed hope it get's live too. will talk with janitor

**Comment by Rushor** [comment] 2019-06-20 08:47
affected creatureid from the dungeons

(39425, 39428, 39788,39587, 39731, 39732, 39378, /*origin*/39625, 40177,40319, 40484, /*grim batol*/44577, 43614, 49045, 43612, 44819);

**Comment by Rushor** [comment] 2019-06-20 08:50
![](https://i.imgur.com/NDHdwcR.jpg)

fixed for all normal bosses of the 3 dungeons

**Comment by giles1508** [comment] 2019-06-28 15:54
ok
this isnt regression
today me and a few members of my guild worked out why this is broke
basically the way the fix was made,   seems to " add 140 points to existing currency "       but  after numberous tests today i can confirm that on my druid which hs done heroics and gained jsutice points before,  he got the reward,   while my level 85 rogue who has never done a heroic before or any instance at all,   didnt receive any,   basically as my rogue hasnt " unlocked "  the justice point currency,   so the fix kitz put in place cannot add to the currency as technically the fresh lvl 85 doesn have any currency there to add to 
so no with this new information to hand,   we can get a different fix in place and test it on toons that have had 0 justice points at all,   as when me and kitz tested this,  we both already had justice points on our characters and thats why it worked for us

**Comment by giles1508** [comment] 2019-06-28 15:58
![WoWScrnShot_062819_165625](https://user-images.githubusercontent.com/50211643/60355149-b5402e00-99c5-11e9-93e7-38d127b4d2e9.jpg)


this is at the end of our last test with me on rogue,  this is after instance completed as you can see 0 justice was added

but in the below 2 screenshots of my druid,  you can see that i gained 140 justice points after doing the normal

![WoWScrnShot_062819_143531](https://user-images.githubusercontent.com/50211643/60355306-f9333300-99c5-11e9-9dbd-bd17c8192ee1.jpg)
![WoWScrnShot_062819_145625](https://user-images.githubusercontent.com/50211643/60355317-ffc1aa80-99c5-11e9-946b-0df5ccee194e.jpg)

**Comment by Kitzunu** [comment] 2019-06-28 18:56
@wow-mania Seems to be related to core...
Could you look into it?

**Comment by giles1508** [comment] 2019-06-29 11:22
Why closed again?  Has it been fixed?

**Comment by Rushor** [comment] 2019-07-15 20:46
so any news on this?

**Comment by Echinaceax** [comment] 2019-09-04 08:26
bosses in Lost City of the Tol'vir are not dropping justice points

1st boss Husam drops 1JP
then all other bosses done (regession from last test) no idea why

**Comment by Echinaceax** [comment] 2019-11-08 02:45
update tonight , we didnt recieve our JP for random Cataclysm dungeon

![randon jp not giving at the end](https://user-images.githubusercontent.com/39439201/68445412-2ac0d400-01da-11ea-921a-858336efe76a.jpg)

**Comment by sarahkay88** [comment] 2019-11-10 11:59
@Rushor iv ran loads of dungeons me ver got any jp. However yesterday I managed to get into the lost city dungeon which triggered my jp to start working. And now every dungeon I go in it started working.

**Comment by Rushor** [comment] 2019-11-19 21:09
i will add a script that gives players on login at lat one justice point. then it should work all

**Comment by Rushor** [comment] 2019-11-19 21:12
hasCurrency
modifyCurrency

**Comment by Rushor** [comment] 2019-12-05 08:04
okay if youd don't have any justive point on logon, you will now get one
![I](https://i.imgur.com/QUfPCr6.png)

i thnk this should fix the logic of the justive point reward.

**Comment by Echinaceax** [comment] 2020-01-09 15:17
@Rushor Seems to be still issues regarding the way JP is given

GM just reported to be that they are getting tickets about the JP issue for finishing the RDF 

### meant to get 140 (seems to not be working correctly) or the Maniac points. 

![randon jp not giving at the end](https://user-images.githubusercontent.com/39439201/68445412-2ac0d400-01da-11ea-921a-858336efe76a.jpg)

need to take another look @Rushor, thanks

**Comment by Xman993** [comment] 2020-04-07 20:02
i finished two dungeons, Throne of the Titans and Blackrock Caverns using RDF, got nothing.

**Comment by Echinaceax** [comment] 2020-04-08 00:44
> Throne of the Titans

Throne of the tides you meant?

blackrock doesnt give @Xman993

**Comment by Xman993** [comment] 2020-04-08 01:58
@Echinaceax yes,  Throne of the Tides

When you are gouping up with RDF u always need to get a reward no matter the dungeon u get.
First Normal RDF of the day gives you Justice Points and gold in our case MP. after u just get gold 
First Heroic RDF of the day gives you Valor Points and gold in our case MP. after you get Justice Points and gold. but now we get nothing.

**Comment by Echinaceax** [comment] 2020-04-08 03:16
@Xman993 yes i know i commented here :)
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2450#issuecomment-572606916

**Comment by Echinaceax** [comment] 2020-05-17 09:49
> @Echinaceax yes, Throne of the Tides
> 
> When you are gouping up with RDF u always need to get a reward no matter the dungeon u get.
> First Normal RDF of the day gives you Justice Points and gold in our case MP. after u just get gold
> First Heroic RDF of the day gives you Valor Points and gold in our case MP. after you get Justice Points and gold. but now we get nothing.

1 issues fixed here now @Xman993 
#4508

**Comment by Echinaceax** [comment] 2020-06-03 15:46
No issue on this anymore i think 
seems to be working since you added the 1jp @Rushor :)

**Comment by Lumber-Jack-2** [comment] 2020-06-04 05:49
Okay closing then?

**Comment by Echinaceax** [comment] 2020-11-18 10:01
@Rushor 
The fix you did by adding 1JP hasnt fixed 

Guildies and GM have told me that they dont get the JP rewards for completing the Cata dungeons on normal (again)
But when GM gets tickets and manually adds 1JP to player it seems to fix their issue

**Comment by mfranca0009** [comment] 2021-02-10 19:54
At or before Patch 4.0.1:
https://www.wowhead.com/news=170048/cataclysm-justice-valor-point-drop-quantities#:~:text=Cataclysm%20bosses%20will%20give%2075,Valor%20Points%20on%2025%2Dplayer

Justice Points Table referencing Cataclysm Expansion (Specific Patch undetermined):
https://www.wowhead.com/currency=395/justice-points

Normal bosses on kill rewarding JP is irrelevant for most dungeons, since from evidence it says nothing of the sort.
Random dungeon finder rewards are properly being handed out, as this was fixed previously here:
#4508 

Recently, there was a player stating they were not receiving these rewards on a RDF queue, but apparently this was a visual bug of only receiving 1 JP even though it actually added the full 140 JP.

Heroic Dungeon Bosses hand out 75 Justice Points each.
10-man raids hand out 75 Valor Points each.
25-man raids hand out 105 Valor Points each.

IF ANY HEROIC DUNGEON BOSSES ARE MISSING THEIR 75 JUSTICE POINT REWARD, OPEN A NEW ISSUE WITH THE SPECIFIC NAME OF THE BOSS THAT NEEDS TO BE FIXED.

**Closed by mfranca0009** 2021-02-10 19:54 UTC
Labels: Confirmed By Tester, Priority-High, Regression
