### ISSUE TITLE
Quest "Diabolical Plans" (26443)  (Ally) - Ashenvale

### ISSUE THREAD

**Issue by ssmilazzo** [WoWManiaUK/Blackwing-Lair#5272] opened 2021-07-05 16:39 UTC
**Links:**

https://www.wowhead.com/quest=26443/diabolical-plans#comments

**What is happening:**

Item to start quest not dropping. Please note here https://github.com/WoWManiaUK/Blackwing-Lair/issues/1196 that Kitzunu commented that this was Horde only, it is not. I have killed 70 -80 mobs that should drop item and am wondering if the item will drop for alliance?

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

**Comment by mfranca0009** [comment] 2021-07-05 16:43
@ssmilazzo This quest is horde-only, per the the WoWhead quest link. If it's not dropping from the proper mobs then it's most likely not in the loot table.

I will look into it.

**Comment by ssmilazzo** [comment] 2021-07-05 16:48
No offense but ya sure 'bout that?
![Screenshot (17)](https://user-images.githubusercontent.com/25713425/124501271-37bb0f80-dd8f-11eb-8df6-7bc43e6ada92.png)

**Comment by mfranca0009** [comment] 2021-07-05 16:53
@ssmilazzo  Yes, I am sure about that. The old issue you referenced has a WoWhead link that literally says Horde only.

Quest ID 26447 is the horde version of the quest :)

**Comment by ssmilazzo** [comment] 2021-07-05 16:58
You are correct. 26443 is the Ally side. It is the same drop item though? Right? So does this item drop for Ally?

**Comment by mfranca0009** [comment] 2021-07-05 16:59
@ssmilazzo Yes, I've verified and confirmed this item is dropping for both Alliance/Horde and it even has a higher drop chance that what it should be. It's still extremely low at a 2% chance. It's just going to be awhile to loot this item from RNG.

The Horde item has a larger drop chance than the Alliance.

**Comment by ssmilazzo** [comment] 2021-07-05 17:01
Thank you for your quick response. You guys are amazing.

**Comment by mfranca0009** [comment] 2021-07-05 17:13
All set now, I'm gonna apologize ahead of time, because I'm required to keep it blizzlike so the drop chance for Alliance is now lower...

Alliance drop chance has been lowered to the correct drop chance of 1.3%, 1.2%, and 1% for Searing Infernal, Roaming Felguard, and Monnoroc Lasher respectively.

Horde drop chance has been adjusted to the correct drop chance of 4%, 3%, and 2% for Roaming Felguard, Searing Infernal, and Mannoroc Lasher respectively.

**Comment by ssmilazzo** [comment] 2021-07-05 17:15
Ironically, I just got it on the 5th kill. 

Thanks for looking into it and no need to apologize.

**Comment by Echinaceax** [comment] 2021-07-05 17:53
confirm fixed in PTR 
drop rate as it should be 👍

**Closed as completed** 2021-07-24 08:01 UTC
Labels: Fixed in Dev - Confirmed by tester
