### ISSUE TITLE
[Guild] Problem with guild inviting, promoting and demoting

### ISSUE THREAD

**Issue by ArccaneR** [WoWManiaUK/Blackwing-Lair#3150] opened 2019-08-24 15:17 UTC
**Links:**
![Screenshot_19](https://user-images.githubusercontent.com/52254524/63639329-829b7480-c69a-11e9-8e24-91b046cb4a6f.png)
![InkedScreenshot_21_LI](https://user-images.githubusercontent.com/52254524/63639332-84653800-c69a-11e9-95f6-3596010533f5.jpg)

from WoWHead or our Armory

**What is happening:**

When I guild invite, promote or demote someone, he dissapears from the guild list, becomes nameless, rankless and zoneless. Pretty much I can't do anything when he is bugged like that. You can see he is still in the guild when you /who him and he can still type in the gchat but he can't be gremoved and his ranks can't be changed. This is a completely fresh bug. It was fine 2 days ago.

**What should happen:**

When I guild invite, promote or demote someone, it should show it in guild chat and the person I've ginvited shouldn't dissapear from the guild list. Pretty much it should work as normally.

**Comment by Eirolla** [comment] 2019-08-24 18:54
![image](https://user-images.githubusercontent.com/26048748/63641582-64913c80-c6b9-11e9-9fb5-7c8d661e354a.png)
Used Command: /who Paradox
Member amounts are not the same on that screenshot.
Explaining: on Guild panel, 4 players showing "online" but /who paradox has 6 player online (there's not have any other paradox guild/area/class)

**Comment by Echinaceax** [comment] 2019-08-24 19:52
@wow-mania this issue needs fixing as the guild cant remove players if needed

**Comment by Echinaceax** [comment] 2019-08-25 13:27
update @wow-mania cant reproduce this bug on dev , doesnt alter the facts that its bugged on live.
is there some GM debug command you can do to fix this guild issue?
Note its 2 seperate guilds that are having this issue

**Comment by kDracku** [comment] 2019-08-26 08:55
Ive encontured problem with notes , even if you have permission to change it , it says you dont have permission.

**Comment by Echinaceax** [comment] 2019-11-30 00:06
Still a major issue 30.11.19

**Comment by Echinaceax** [comment] 2020-03-26 19:55
Any update reagarding these issues 
GMs are getting tickets about these issues now and have asked when these will be looked into

**Comment by Echinaceax** [comment] 2020-11-21 02:04
#1873
#3159
#3992 

adding these here so i can close the others

**Comment by Echinaceax** [comment] 2021-01-22 17:39
closing this for now seems its ok

**Closed by Echinaceax** 2021-01-22 17:39 UTC
Labels: Guild related, Priority-High
