### ISSUE TITLE
[NPCs] Missing Quest NPCs - Azshara

### ISSUE THREAD

**Issue by polymorphism98** [WoWManiaUK/Blackwing-Lair#4502] opened 2020-05-14 07:54 UTC
**Links:**
https://www.wowhead.com/npc=36384/zapper-gnome
https://www.wowhead.com/npc=36385/netgun-gnome

**What is happening:**
1. Go to Azshara at around (43, 82).
2. The above mentioned NPCs are not present for the player to kill.
3. These NPCs are required for the quest: [The Terrible Tinkers of the Ruined Reaches](https://www.wowhead.com/quest=14383/the-terrible-tinkers-of-the-ruined-reaches)

**What should happen:**
1. There should be multiple number of these NPCs present at the coordinates provided above.
2. Players should be able to kill the NPCs and complete the above mentioned quest.

**Is it crashing the server?:** No

**Other Information:**
1. Another required NPC for this quest is [Bingham Gadgetspring](https://www.wowhead.com/npc=36407/bingham-gadgetspring). But he is already present at this location. It was fixed as a part of this issue [#972](https://github.com/WoWManiaUK/Blackwing-Lair/issues/972)

**Comment by mfranca0009** [comment] 2020-06-29 16:31
More NPCs added, still working on movement. It seems some were on waypoints moving up and down the hill in the area of the quest while some were just wandering near their spawn point.

**Comment by mfranca0009** [comment] 2020-06-29 17:57
Complete. Added more mobs, added waypoint data to two mobs that walks up/down hill in that area (2 hills), and adjusted smart AI scripts for these two mob types because they were self casting their spells and they weren't casting them on the player character.

Needs testing in PTR. 👍

**Comment by Echinaceax** [comment] 2020-06-29 21:10
Confirmed fixed - more added 

Just some pathing issues with 36384/zapper-gnome glitching on the mountain :)
https://gyazo.com/1434475f256171d76c7ff0eabbb46c6f
https://gyazo.com/9079aa8fc71ee9f80fc123f366066eee

**Comment by mfranca0009** [comment] 2020-06-30 02:06
The glitches happening from netgun gnome (guid 284864)  and zapper gnome (guid 284863) should be fixed. Instead of keeping them on random movement based on the distance from their spawn point, I put them on waypoint movement and setup waypoints for them.

Let me know if this works out better 👍

**Comment by Echinaceax** [comment] 2020-06-30 09:14
Much better @mfranca0009  thanks :)

**Closed as completed** 2020-07-08 14:17 UTC
Labels: Fixed in Dev - Ready to test, Fixed in Dev - Confirmed by tester, Confirmed By Tester, Starting Zone, Missing NPC
