### ISSUE TITLE
[Quest] A Destiny of Flame and Sorrow - 28218- Felwood

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#814] opened 2019-03-07 11:13 UTC
**Links:**
quest - https://www.wowhead.com/quest=28218/a-destiny-of-flame-and-sorrow

**What is happening:**

- Auto completing without doing anything

**What should happen:**
- I should have a fight with Arthas 

video - https://www.youtube.com/watch?v=3jtVIF7zJrQ

**Comment by Dranah** [comment] 2019-05-04 16:52
Confirmed.
Also, this quest should not be available before completing https://www.wowhead.com/quest=28217/wanted-the-demon-hunter
The reason for this is that the NPC is supposed to be hostile until you fight him, get the above quest complete, hand it in and he offers this quest, which is the next in chain.
The fix need to be done at once:
- Make NPC hostile until fought
- Make him turn friendly when defeated and the quest 28217 completed
- Quest 28218 is now unlocked.

**Comment by Echinaceax** [comment] 2020-06-27 22:37
WANTED: The Demon Hunter fixed now https://github.com/WoWManiaUK/Blackwing-Lair/issues/815

**Comment by mfranca0009** [comment] 2020-12-31 20:54
The quest order for Feronas Sindweller quest chain in Felwood should be all set now 👍 

Working on getting the battle with Arthas fixed now.

### SPELLS
Green Channeling (Feronas) - https://www.wowhead.com/spell=13540/green-channeling
Anti-Magic Zone (Area / Romo's Standard Bunny) - https://www.wowhead.com/spell=89703/anti-magic-zone-cosmetic-green-giant

### NPCS
Illidan Stormrage - https://www.wowhead.com/npc=47735/illidan-stormrage
Arthas - https://www.wowhead.com/npc=47733/arthas

**Comment by mfranca0009** [comment] 2021-01-01 02:47
This should now be all set, scripted the events, Arthas and Illidan have proper abilities, proper text lines, and you get quest credit at the end of the event. Needs testing in PTR 👍

**Comment by Echinaceax** [comment] 2021-01-01 23:54
comfirmed fixed in ptr by Valk

**Closed** 2021-01-06 11:41 UTC
Labels: Confirmed By Tester, Fixed Confirmed, Fixed in Dev, Low Priority, On .BQ command, Quest, zone 40-50
