### ISSUE TITLE
[NPC] Initiate Goldmine Twilight Highlands (issue 2)

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#1897] opened 2019-05-15 18:40 UTC
**Links:**

https://www.wowhead.com/quest=27782/mathias-needs-you

**What is happening:**
(as horde)
It gives me alliance quest
**What should happen:**
Im not alliance

**Comment by sarahkay88** [comment] 2019-05-17 18:24
NPC ID - https://www.wowhead.com/npc=46243

**Comment by mfranca0009** [comment] 2020-12-22 23:15
Ran into this issue on live, confirmed.

**Comment by mfranca0009** [comment] 2021-02-07 19:24
This is the same as #5059, since I already marked 5059 as fixed, I'm closing this out as a duplicate.

**Closed by mfranca0009** 2021-02-07 19:24 UTC
Labels: Confirmed By Tester, Wrong Faction, zone 80-85 Cata
