### ISSUE TITLE
[Bastion of Twilight] Theralion and Valiona Heroic - No Portal or to Fast despawn in Twilight Realm

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3804] opened 2019-11-03 16:24 UTC
**Links:**

from WoWHead or our Armory

**What is happening:**

you cant leave the twilight realm cause  there is no portal in the other realm.

**What should happen:**

there should be an portal like in normal mode to leave the realm

**Comment by Batraneluu** [comment] 2019-11-03 16:51
Portals exists but they dissapear after a period of time , if you join exactly after the transition you will have 2 -3 portals but when you finished killing the ADDS on other realm no more portals for you, it's an ugly bug.

**Comment by Slydee23** [comment] 2019-11-03 17:28
thx for the info

**Comment by Rushor** [comment] 2019-11-05 19:41
Will assign this to you @Keader - hope you can help me :>

**Comment by Keader** [comment] 2019-11-16 14:35
Not a bug.

> Being struck by Theralion's Dazzling Destruction or Valiona's Deep Breath pulls players into the Twilight Realm. In this alternate plane of existence, spheres of volatile twilight energy float around and detonate if touched. Collapsing portals appear randomly throughout the area, and players may use a portal to return to the material plane. **Each portal disappates after a time.** In Heroic Difficulty Shifting Reality also pulls players into the Twilight Realm.


https://wow.gamepedia.com/Valiona_and_Theralion

You have 60 sec after each portal vanish

**Comment by Slydee23** [comment] 2019-11-17 10:59
after we got down ther is no portal after some seconds we checked it now multiple times in different weeks

**Comment by Keader** [comment] 2019-11-17 13:51
I found the problem.
Was only working in 10 man (normal)
10 man heroic, 25 man (normal/heroic) was not working.
Fixed.

**Comment by Slydee23** [comment] 2019-11-17 17:58
Thank You

**Comment by Slydee23** [comment] 2019-11-24 13:49
Portal now deaspawns after 1 player used it so its only one time use the others stuck now there

**Closed** 2019-12-02 13:25 UTC
Labels: Dungeon/Raid, Fixed in Dev, Priority-High, Regression
