### ISSUE TITLE
[Quest] The Maelstrom-Port broken 

### ISSUE THREAD

**Issue by Axilles89** [WoWManiaUK/Blackwing-Lair#2566] opened 2019-06-26 23:50 UTC
**Links:**
https://www.wowhead.com/quest=27203/the-maelstrom

**What is happening:**
When you take the portal after receiving the quest it ports you directly into Deepholm.

**What should happen:**
It should port you to an area to interact with Thrall and then proceed into the Maelstrom.

**Comment by giles1508** [comment] 2019-06-27 05:56
Duplicate of  #2565

**Closed by giles1508** 2019-06-27 05:56 UTC
