### ISSUE TITLE
[Glyph] of spirit tap (priest)

### ISSUE THREAD

**Issue by hediunchained** [WoWManiaUK/Blackwing-Lair#2769] opened 2019-07-17 13:38 UTC
**Links:**

https://wow.gamepedia.com/Glyph_of_Spirit_Tap

**What is happening:**
it does not procc the buff that gives back mana after killing a target that gives xp/honor with shadow word death

**What should happen:**
it gives a buff that return back 12% mana over 12 sec after killing a target that gives xp/honor with shadow word death

**Comment by hediunchained** [comment] 2019-07-20 12:15
i dont know if a fix has been deployed for this issue but it seems that it now seems to work only if the target has lower health than the initial shadow word death dmg (without talent and 25% remaining health amplification) 
exp : my shadow word death tooltip says that it deals 500 dmg, and my target has lower or equal health, then the glyph procs

**Comment by Keader** [comment] 2019-07-20 12:16
wut?
@Dranah can you understand/check?

**Comment by hediunchained** [comment] 2019-07-20 12:22
let me reform,
my shadow word death deals normal dmg without talent and the target having more than 25% hp right ?
now when the target have 25% or lower hp the damage is *3.
now the glyph only work if the target is killed while having hp equal or lower to that initial normal dmg
![WoWScrnShot_072019_131907](https://user-images.githubusercontent.com/36192411/61578585-bf9fa480-aaf9-11e9-9fb1-fea4875f74f8.jpg)
![WoWScrnShot_072019_131908](https://user-images.githubusercontent.com/36192411/61578587-c201fe80-aaf9-11e9-878c-f06cfc8520bb.jpg)

**Comment by hediunchained** [comment] 2019-07-20 12:23
tested it several times and i can confirm it

**Comment by Keader** [comment] 2019-07-20 12:27
Hmm got it now.
Let me test and if found any problem i will fix.

**Comment by hediunchained** [comment] 2019-07-20 12:29
sure thing, thanks for the quick response.

**Comment by Keader** [comment] 2019-07-20 12:51
Found the cause.
Fixed in PTR.

**Closed** 2019-07-22 10:17 UTC
Labels: Class, Fixed in Dev, Regression
