### ISSUE TITLE
[Rogue][Talent] Overkill buff timer not reseting correctly

### ISSUE THREAD

**Issue by Calmwindx** [WoWManiaUK/Blackwing-Lair#4513] opened 2020-05-19 15:22 UTC
**Links:**
https://cata.cavernoftime.com/spell=58427

from WoWHead or our Armory

**What is happening:**
The rogue talent Overkill is not working correctly. Whenever you exit stealth you should get a 20 second timer on Overkill. However, if you exit stealth, then re-enter it and exit again before the first 20 second timer is up, the buff is not refreshed and will expire after the first 20 second timer.

**What should happen:**
Entering stealth normally, or by Vanish should reset the timer on overkill.

**Is it crashing the server?:**
Nope.

**Other Information:**
If you stay in stealth longer than the first 20 second timer, the overkill buff does reset, it just wont reset the timer till the first is finished.

**Comment by mfranca0009** [comment] 2021-02-15 20:57
I confirmed this, it was counting the original 20 second timer and removing the buff after 10 seconds of leaving stealth the second time.

**Now with fix:**

- [x] Timer executed on leaving Stealth
- [x] If going back into stealth, the original timer will be removed.
- [x] Leaving stealth again, you'll have a fresh timer of 20 seconds when overkill will be removed.

I tested this fix with Vanish as well, and since vanish transitions you into normal stealth, it seems to work fine as well now 👍

**Comment by golosomie** [comment] 2021-02-19 22:33
@mfranca0009 Confirmed fixed on PTR. Working with normal stealth and Vanish as expected.

**Closed as completed** 2021-02-24 14:04 UTC
Labels: Fixed in Dev - Ready to test, Fixed in Dev - Confirmed by tester, Confirmed By Tester, Class/Spells

**Comment by Yamios** [comment] 2021-07-10 09:52
Now there is another bug in overkill if you leave stealth and respec to subtlety before the buff expire . OverKill buff stay in subtlety and never expire .

**Comment by mfranca0009** [comment] 2021-07-10 15:54
@Yamios This is a different problem than the original issue. Please open a new issue and report it.
