### ISSUE TITLE
[quest=24861] [Last Rites, First Rites] - Camp Narache 

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#862] opened 2019-03-10 17:34 UTC
**Links:**
[quest=24861]
https://www.wowhead.com/quest=24861/last-rites-first-rites
from WoWHead or our Armory

**What is happening:**
This quest gets completed just by moving a few steps.
I dont need to click on the item as i should do

**What should happen:**
You should click on your item to complete the quest.

**Comment by Echinaceax** [comment] 2019-03-10 18:14
> This quest gets completed just by moving a few steps.

On what class ?
In general or a specific class?

**Comment by Saintres** [comment] 2019-05-05 14:12
All classes, and still not working

**Comment by Saintres** [comment] 2019-05-05 14:18
Ohh damn i made a dodo, changed this tag to another quest with same name.

**Comment by mfranca0009** [comment] 2021-05-28 01:46
Missing the whole interaction of each trainer kneeling before Greatmother Hawkwind's grave while Chief Hawkwind speaks. He speaks but none of them kneel on quest accept.

Also, the trigger is visible to players, and the item can't actually be used because it doesn't register that you are near the trigger.

**Comment by mfranca0009** [comment] 2021-05-28 03:46
All set 👍

**Comment by golosomie** [comment] 2021-05-28 18:16
Confirmed fixed on PTR. Quest item only usable on the correct location, credit is given when using the item. Even the emote on accepting works!

**Closed** 2021-06-08 15:27 UTC
Labels: Fixed in Dev - Confirmed by tester, Fixed in Dev - Ready to test, Priority-Low, Starting Zone
