### ISSUE TITLE
[Quest] The Egg Lives On - unscripted/autocomplete - Badlands

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#598] opened 2019-01-17 13:40 UTC
https://www.wowhead.com/quest=27859/the-egg-lives-on

Event unscripted, the quest is simply autocomplete at the NPC https://www.wowhead.com/npc=46664/dr-hieronymus-blam

**Comment by mfranca0009** [comment] 2020-06-28 04:31
Every video on WoWhead for this quest shows it as an auto turn-in. Is there suppose to be a cut-scene?

**Comment by Echinaceax** [comment] 2020-06-28 09:04
No idea @mfranca0009 the old tester isnt here anymore 

I believe she meant from the previous quest before it https://www.youtube.com/watch?v=94OcsU9UH-k  

**side note:** there was a missing npc issue reported for that quest https://github.com/WoWManiaUK/Blackwing-Lair/issues/2289 and no further test was reported about a cutscene for that after the npc was fixed. so Yes as seen in video its the issue with the https://www.wowhead.com/quest=27897/the-hidden-clutch quest really and not the The Egg Lives On

**Comment by mfranca0009** [comment] 2020-06-28 18:46
Alliance: https://www.wowhead.com/quest=27858/rheastraszas-gift
Horde: https://www.wowhead.com/quest=27898/rheastraszas-gift

This is the quest from "Rhea" that has a cut-scene which does not work. Issue already opened about it here, #3380 

Probably just close this issue then, since "The Egg Lives On" is an auto-complete quest and works as intended.

Video: https://www.youtube.com/watch?v=uCWiS-c_JI0

**Closed** 2020-06-28 21:29 UTC
Labels: Low Priority, zone 40-50

**Comment by Echinaceax** [comment] 2020-06-28 21:31
thanks @mfranca0009 
i agree this is as intended, no issue regarding this quest its the others
