### ISSUE TITLE
[Quest] Into the World of Spirits ID 11333 - Howling Fjord

### ISSUE THREAD

**Issue by Felfyre** [WoWManiaUK/Blackwing-Lair#1355] opened 2019-04-04 19:02 UTC
**Links:**
https://www.wowhead.com/quest=11333/into-the-world-of-spirits
https://www.wowhead.com/item=33635/reagent-pouch
from WoWHead or our Armory

**What is happening:**

No reagent pouches spawned

**What should happen:**

There should be punches spawned around both wrecks. According to WoWHead comments, multiple spawns are the norm

**Comment by Echinaceax** [comment] 2019-04-05 18:57
![under](https://user-images.githubusercontent.com/39439201/55650206-62e7da80-57e5-11e9-97e6-b4822cf22655.jpg)

**Comment by Felfyre** [comment] 2019-04-05 19:05
This is dev or live version?

**Comment by Echinaceax** [comment] 2019-04-05 19:09
> This is dev or live version?

Sorry Dev :)

**Comment by Rushor** [comment] 2019-04-05 22:17
all stuff that is fixed is on "dev" in first place :) Once the issue is closed it is on live version

**Closed** 2019-04-10 12:37 UTC
Labels: Fixed Confirmed, Fixed in Dev, Minor - 50+
