### ISSUE TITLE
[Repeteable quest] Tokens of the Descendants

### ISSUE THREAD

**Issue by Scratcheeees** [WoWManiaUK/Blackwing-Lair#4268] opened 2020-03-12 15:48 UTC
**Links:**

https://cata-twinhead.twinstar.cz/?quest=11074

from WoWHead or our Armory

**What is happening:**

Can't turn the items in the daily quest.

**What should happen:**

You should get and item to kill an add that gives you 525  Sha'tari skyguard rep.

**Comment by Echinaceax** [comment] 2020-03-12 16:11
GM spoke to me about this just now and He explained all

@Rushor 
From what the GM said is that After you have completed [Adversarial Blood](https://cata-twinhead.twinstar.cz/?quest=11885) then this quest [Tokens of the Descendants](https://cata-twinhead.twinstar.cz/?quest=11074) becomes a daily quest. 

The thing is the reporter wasnt given the [Tokens of the Descendants](https://cata-twinhead.twinstar.cz/?quest=11074) quest at all, so the GM added it for them to test if He could hand it back in and check a few other things.

seems the quest order or something is wrong, because they wasnt given [Tokens of the Descendants](https://cata-twinhead.twinstar.cz/?quest=11074) when the only requirement was that they needed to have completed [Adversarial Blood](https://cata-twinhead.twinstar.cz/?quest=11885)

**Quest order**
https://wowwiki.fandom.com/wiki/Quest:Tokens_of_the_Descendants


Video - https://www.youtube.com/watch?v=_vdFxtsdMjE

**Comment by Echinaceax** [comment] 2021-06-01 12:47
UPDATE

ok, i see the issue myself now @mfranca0009 

after you have completed all the quests leading upto Adversarial Blood and delivering it, then the repeatable quest  Tokens of the Descendants is activated, but is missing  https://cata-twinhead.twinstar.cz/?quest=11074 from Hazzik https://cata-twinhead.twinstar.cz/?npc=23306 to deliver the items back

Akkarai's Talons https://cata-twinhead.twinstar.cz/?item=32715
Karrog's Spine https://cata-twinhead.twinstar.cz/?item=32717
Gezzarak's Claws https://cata-twinhead.twinstar.cz/?item=32716
Vakkiz's Scale https://cata-twinhead.twinstar.cz/?item=32718


![image](https://user-images.githubusercontent.com/39439201/120325366-dc0cea80-c2e7-11eb-8535-5c1b0e7b93ec.png)

**Comment by mfranca0009** [comment] 2021-06-01 19:37
All set 👍

**Comment by Echinaceax** [comment] 2021-06-01 20:46
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/120388298-37140100-c32b-11eb-9558-316984b3e126.png)

**Closed** 2021-06-08 15:21 UTC
Labels: Confirmed By Tester, Fixed in Dev - Confirmed by tester, Fixed in Dev - Ready to test
