### ISSUE TITLE
[Quest] Violent Gale

### ISSUE THREAD

**Issue by questbugreporter** [WoWManiaUK/Blackwing-Lair#3734] opened 2019-10-25 11:03 UTC
https://www.wowhead.com/quest=26426/violent-gale
from WoWHead or our Armory

**What is happening:**

Finding the entrance to to Crumbling Depths doesn't complete the second quest objective.

**What should happen:**

Finding the entrance to to Crumbling Depths should complete the second quest objective.

**Comment by Rushor** [comment] 2019-10-25 11:12
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/1995

**Closed by Rushor** 2019-10-25 11:12 UTC
