### ISSUE TITLE
[Quest] The Light's power - ID 26966 - Azuremyst

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#872] opened 2019-03-10 20:02 UTC
**Links:**
Quest - https://www.wowhead.com/quest=26966/the-lights-power
NPC - https://www.wowhead.com/npc=16501
from WoWHead or our Armory

**What is happening:**
This quest should be available at level 3 from the NPC -Aurelon - https://www.wowhead.com/npc=16501
to learn seal and judgement and use judgement on training dummy. But the quest is not there, check both male and female draenei both have same issue

**What should happen:**
This quest should be available at level 3 from the NPC -Aurelon - https://www.wowhead.com/npc=16501
to learn seal and judgement and use judgement on training dummy to complete quest.

**Comment by mfranca0009** [comment] 2021-05-28 05:53
This NPC does hand out the quest, but you have to finish Quest 9287 first because it's a prerequisite.

Quest required: https://www.wowhead.com/quest=9287/paladin-training

BUT I will also check if its working properly, since most of these quests were not.

**Comment by Echinaceax** [comment] 2021-05-28 12:04
@mfranca0009 from what i can find the prequest was removed 

https://wowpedia.fandom.com/wiki/Paladin_Training

![image](https://user-images.githubusercontent.com/39439201/119981183-a0a7ae80-bfbd-11eb-83a6-bc84f3916af3.png)

where as cavern has http://cata.cavernoftime.com/quest=9287
and twinstar the same https://cata-twinhead.twinstar.cz/?quest=9287

either twinstar and caven didnt check wowpedia.fandom or wowpedia.fandom is wrong lol 

looks like this quest was added to replace the older prequest 

https://wowpedia.fandom.com/wiki/The_Light%27s_Power

![image](https://user-images.githubusercontent.com/39439201/119986081-b6b86d80-bfc3-11eb-875c-0bc1e4d4d15c.png)

**Comment by mfranca0009** [comment] 2021-05-30 02:50
Referencing this: https://cata-twinhead.twinstar.cz/?quest=26966

The quest will now have prerequisite for: https://cata-twinhead.twinstar.cz/?quest=9283 (Rescue The Survivors!)

The old deprecated quest removed in 4.0.3a will be disabled 👍

**Comment by mfranca0009** [comment] 2021-05-30 03:04
All set 👍

**Comment by Echinaceax** [comment] 2021-05-30 20:45
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/120119544-8aa21580-c198-11eb-8dff-1b982adae78b.png)
![image](https://user-images.githubusercontent.com/39439201/120119570-bde4a480-c198-11eb-8c2e-355f866c0422.png)

**Closed** 2021-06-08 15:27 UTC
Labels: Fixed in Dev - Confirmed by tester, Fixed in Dev - Ready to test, On .BQ command, Quest, Starting Zone
