### ISSUE TITLE
[spell] Savage Roar - Drui - no damage buff

### ISSUE THREAD

**Issue by fuzzydunlop** [WoWManiaUK/Blackwing-Lair#2327] opened 2019-06-11 17:20 UTC
**Links:** WowHead link expired (old spell), Reign Armory non-existent.

**What is happening:** There seems to be no damage buff, at all.

**What should happen:** Autoattacks (white hits) should do 80% more damage while savage roar is active. I did some testing and there's no increase. Took a screen shot of dmg with SR up, and one without SR active. The averages and the min-max are the same.  

![WithSR](https://user-images.githubusercontent.com/14002052/59292238-f8d43180-8c7c-11e9-8ce9-8240af8cc0c1.jpg)

**Comment by giles1508** [comment] 2019-06-13 15:39
confirmed today by myself while testing,   this does NO increased damage,  and this is a kitty druids bread and butter attack dmg ( melee auto hits )  should be pretty much top of a ferals dmg chart when atm its half way down the list.   this needs to be fixed ASAP  gimping ferals alot !

**Comment by fuzzydunlop** [comment] 2019-07-05 22:22
Any idea when this fix is ready ? Been a while now and no clue what the status of this one is =)

**Comment by Sevenblade11** [comment] 2019-07-15 21:25
Any updates? It's a taaaaadd bit important for Feral DPS

**Comment by Keader** [comment] 2019-07-15 21:26
Yeah, but no one signed me since 2 days Ago.
So Will be fixed next week

**Comment by Keader** [comment] 2019-07-17 13:39
Fixed.

**Closed** 2019-07-20 09:00 UTC
Labels: Class, Confirmed, Fixed in Dev, Priority-High
