### ISSUE TITLE
[Spell/Racial] Cultivation - Spell ID 20552 (It doesnt work! @Rushor)

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2664] opened 2019-07-06 18:22 UTC
I spoke with a GM, due to Rushor's call, he removed the spell of my character, and readded it.
Casting speed of herb gathering is still 2 seconds. With the tauren buff it should be, in cataclysm, **0.5 Seconds.**

So unlike Rushor said it is not a problem, it is. **But only on the SPEED side, the 15 skillpoints are working!**

I can see also the 15 points in Herbalism added to my profession, but the part which speaks "(...) and you gather herbs **faster** than normal herbalists." **isnt.**

Below i added my issue again with all the links and problems. Please read it clearly, its just about the **gathering speed.**

**Links:**
https://www.wowhead.com/spell=20552/cultivation
from WoWHead or our Armory

**What is happening:**

No increase of **herb gathering speed** as **Tauren** through **"Cultivation"**

**What should happen:**

Taurens should be able through "Cultivation" to **gather herbs faster** than other races.

**Notes**

You can read in the comments on wowhead how it was on Retail. Casting speed should be 0.5 seconds **with Cultivation racial/as Tauren**.

Here it is still 2 Seconds **with "Cultivation"**
It is not character specific, its a problem with the spell itself.

Greetings Lerixo

**Comment by Kitzunu** [comment] 2019-07-06 19:13
Duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/2465

**Closed by Kitzunu** 2019-07-06 19:13 UTC
