### ISSUE TITLE
[Map Tracking] Questlog etc...

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#857] opened 2019-03-10 14:11 UTC
_The quest map bug issue_ 

- Ive has an Idea

**What is happening:**
- As you know the track quest map isnt showing quests on map etc...
- Well ive been thinking this for a while, that when you collect quests in (WOTLK) quest automatically add to your questlog.

- Here in Cata it doesnt, you have to manually track quests

**What should happen:**
- upon collection of the quests they are automatically added to a persons questlog 
- Un track is manual (in my experience)

Could look into the settings regarding questlog and its behavior

just a thought :)

**Comment by Rushor** [comment] 2019-03-10 19:18
yes everything has to be added manually in quest_poi

**Comment by Echinaceax** [comment] 2019-03-10 19:27
yes ..but in RED and in retain cata it wasnt manual im sure 

Could this be why the quest tracking is crappy at times?

**Comment by Kitzunu** [comment] 2019-03-10 19:58
Duplicate of #870

**Closed by Kitzunu** 2019-03-10 19:58 UTC
Labels: Duplicate
