### ISSUE TITLE
[NPC] Shalla Whiteleaf <Druid Trainer> Orgrimmar 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1955] opened 2019-05-18 16:38 UTC
**Links:**
https://www.wowhead.com/npc=44726/shalla-whiteleaf

**Spell IDs**
swift flight form 40120 
flight form 33943

**What is happening:**
swift flight form 40120 overwrites the flight form 33943 which in turn makes trainers believe the druid hasnt trained it in the first place ..costing the player money each time  

**What should happen:**
System should know if spell is learnt already

**Comment by Echinaceax** [comment] 2019-05-18 16:46
same on ally

**Comment by Kitzunu** [comment] 2019-05-21 06:56
Duplicate of #1953

**Closed by Kitzunu** 2019-05-21 06:56 UTC
Labels: Class, Duplicate, Major City
