### ISSUE TITLE
[Fishing Dailies] Darnassus - Solution!

### ISSUE THREAD

**Issue by focarol** [WoWManiaUK/Blackwing-Lair#4265] opened 2020-03-11 06:53 UTC
Topic already mentioned in #2066

You don't get the Kaldorei Herring in Rut'theran (as mentioned in the Quest-Text)
You don't get the Kaldorei Herring in Darnassus.

Solution
The Lake near Dolanaar --> There you can catch the Kaldorei Herring.

Have a nice Day

**Comment by Echinaceax** [comment] 2020-03-11 08:28
Thanks @focarol 
Ive added your solution to the main report, so i will close this one as its not a Bug :)

**Closed** 2020-03-11 08:28 UTC
