### ISSUE TITLE
[Quest] Lieutenant Paval Reethe (Quest Double Ups) - Dustwallow Marsh

### ISSUE THREAD

**Issue by Alethalen** [WoWManiaUK/Blackwing-Lair#4205] opened 2020-02-10 03:41 UTC
**Links:**
https://classic.wowhead.com/quest=1252/lieutenant-paval-reethe
from WoWHead or our Armory

**What is happening:**

double quest QID: 1252

**What should happen:**

**Comment by Echinaceax** [comment] 2020-02-10 12:39
Series show that its meant to be this way (i think) 

![series](https://user-images.githubusercontent.com/39439201/74150533-68366280-4c0a-11ea-9140-78f79e24f0b0.jpg)

how i see it is that, they actually have different objectives from what i can see 

**Lieutenant Paval Reethe**
_Bring Reethe's Badge to Captain Garran Vimes in Theramore._

**Lieutenant Paval Reethe**
_Find out more about Reethe from Adjutant Tesoran in Theramore._

**Comment by mfranca0009** [comment] 2020-08-20 04:16
There are duplicates showing, this is because Horde is getting shown Alliance quests as well.

**Comment by Echinaceax** [comment] 2021-02-07 21:04
confirmed fixed in PTR 

![image](https://user-images.githubusercontent.com/39439201/107159468-7a1f2280-6990-11eb-9b03-f2c81b1166f2.png)

**Closed** 2021-02-11 11:10 UTC
Labels: Confirmed By Tester, Fixed Confirmed, Fixed in Dev, Wrong Faction, zone 30 - 40
