### ISSUE TITLE
[Talent/Hunter] Serpent Spread

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2182] opened 2019-06-01 08:49 UTC
**Links:**

http://cata-shoot.tauri.hu/?spell=87935

**What is happening:**

Doesn't work at all.

**What should happen:**

Multi-Shot should also apply Serpent Sting on all targets hit.

**Comment by gitkulu** [comment] 2019-06-01 08:57
Duplicate of #2068

**Closed** 2019-06-01 12:17 UTC
Labels: Class
