### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by Masqumx** [WoWManiaUK/Blackwing-Lair#4996] opened 2020-12-30 00:18 UTC
Game craching after released from body in RAID and dungon
![IMG_20201229_235642](https://user-images.githubusercontent.com/74605782/103322061-e70fd600-4a3c-11eb-84c4-bbfa2281db5d.jpg) not only me got it

**Comment by Echinaceax** [comment] 2020-12-30 09:42
@Masqumx 
need a few more details 

1. Is it only happening when you click release to graveyard ?
2. Did other players crash in the same way?
3. is it only after a wipe of the group or some crashed when still alive ?

the more info the devs have the more they can try an  pin point why this is happening 


I do believe is could be an addon issue, coz i just searched the error on google and the steps there are what the GMs and devs usually advise us to try @Masqumx 

1. so disable addons and run a few dungeons and see if you crash again
3. then re add the addons 1 by 1, slow process but better than devs trying to find the cause if its not a client / launcher issue 

3. try updating DBM

**Comment by mfranca0009** [comment] 2020-12-30 16:44
Yes, I sent Masqumx a support link that should help him pinpoint the problem, error 132 is mainly from corrupted or out-of-date addon conflicting with the game. It could also be due to out-of-date drivers or software on PC conflicting with game. @Echinaceax

**Comment by Echinaceax** [comment] 2021-05-07 16:44
no new info
closing for now

**Closed as completed by Echinaceax** 2021-05-07 16:44 UTC
