### ISSUE TITLE
[Quest] Curtail the Darktail - Blasted Lands

### ISSUE THREAD

**Issue by mizsh** [WoWManiaUK/Blackwing-Lair#4426] opened 2020-04-28 11:42 UTC
Quest: https://www.wowhead.com/quest=25709/curtail-the-darktail

**What is happening:**
1. Cannot activate the Enohar's Explosive Arrows in order to kill the Darktail.

**What should happen:**
2. Can be activate the Enohar's Explosive Arrows in order to kill the Darktail.

**Comment by Truthseerguy** [comment] 2020-07-19 09:24
Completely bugged. Enohar's arrows can be used, but they have no effect on the Darktail targets. Attempting to attack them with spells is also impossible since they are out of range although they can be targeted and the spell activation dot indicates they are within attack range. The Darktails appear to be hovering just above the ground, however, standing under them indicates that both Enohar's arrows and player spells are out of range. Moving away from them allows arrows to be fired to no effect, but spells cannot be cast.

**Comment by mfranca0009** [comment] 2020-07-29 02:46
Figured I'd confirm this, just witnessed it on live and quest can not be completed. Mobs are bugged due to a movement inhabit type incorrect and quest item / spell seems to do nothing at all.

**Comment by mfranca0009** [comment] 2020-07-30 16:37
The spell attached to quest item is completely messed up. Does not shoot flaming arrow like it should, only shows animation of shooting a bow with no arrow actually being shot.

Spell that shows what should happen: https://www.wowhead.com/spell=78834/flaming-arrow-hit
Quest Item Spell that needs to be adjusted and kill darktails: https://www.wowhead.com/spell=78838/enohars-explosive-arrow

**Comment by mfranca0009** [comment] 2020-07-30 21:55
C++ Script made, waiting on it to be applied for testing and further adjustments 👍

**Comment by mfranca0009** [comment] 2020-08-03 04:04
C++ script applied and working as intended, needs testing in PTR 👍

**Comment by Echinaceax** [comment] 2020-08-03 08:33
Confirmed fixed in PTR 
https://gyazo.com/a017d27395d4ad6e408ce18caf9841c9

note: i did however see some of the Darktail targets have wider hitboxes than the others 
(you will see at the end of the video) linked above @mfranca0009

**Comment by mfranca0009** [comment] 2020-08-03 15:22
This should be accurate on the miss spell, its suppose to be slightly farther away from mob and then it will aggro you for range of combat

**Closed as completed** 2020-08-11 09:06 UTC
Labels: Fixed in Dev - Ready to test, Fixed in Dev - Confirmed by tester, Confirmed By Tester
