### ISSUE TITLE
[quest] Something brewed

### ISSUE THREAD

**Issue by Wojtek92** [WoWManiaUK/Blackwing-Lair#3437] opened 2019-09-26 20:22 UTC
**Links:**
https://www.wowhead.com/quest=28409/something-brewed
from WoWHead or our Armory
https://www.wowhead.com/quest=28409/something-brewed
**What is happening:**
there should be an event performed with caravan 
nothing is happening

**What should happen:**

there should be an event performed with caravan

**Comment by Kitzunu** [comment] 2019-09-26 20:34
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/287

**Comment by Rushor** [comment] 2019-09-26 22:50
thanks kitz :> love you

**Closed by Rushor** 2019-09-26 22:50 UTC

**Comment by Kitzunu** [comment] 2019-09-27 12:10
@Rushor ♥️
