### ISSUE TITLE
[Spell/Druid] Wild Growth Only Targeting 1 Party Member

### ISSUE THREAD

**Issue by Brockers1** [WoWManiaUK/Blackwing-Lair#2248] opened 2019-06-03 19:39 UTC
**Links:**

from WoWHead or our Armory

**What is happening:**
When you cast wild growth on a party member it does not apply to 5 party/raid members as it says on the tooltip. Only one is affected that you cast it on

**What should happen:**
5 Party members within 30 yrds should receive the HoT

**Comment by Brockers1** [comment] 2019-06-03 19:42
Thought this was easy to replicate so haven't included any SS or video. I can recreate the issue 100% of the time and never seen it work as intended. If you need any further info:

Discord: Brockers

IGN: Brockers, Brocker, Impaqt, Exci

**Comment by zippoking** [comment] 2019-06-03 19:50
I don´t think it should always apply to 5 party/raid members. The tooltip says "up to 5", doesn´t that mean 1-5? Otherwise it would say "heals 5 players"

![Wild Growth - Definition](https://user-images.githubusercontent.com/18005338/58829961-6fec4300-8649-11e9-8f98-a5c10367fd2e.PNG)

**Comment by Brockers1** [comment] 2019-06-03 19:59
I believe the 'Up to' specifically relates to the players within 30 yards of the character that receives the initial buff. It's not RNG.

Scenario #1:
All 5 Players are stacked within 5yds

If I cast the spell on any player all Players should receive wild growth

Scenario #2:
2 Players are further than 30 yards from the target:
The two players out of range will not receive the buff but the remaining 3 should.

Currently in my experience only the below is happening
Scenario #3:
All 5 players are within 30 yards and only the target receives the buff, regardless of who I cast it on

**Comment by Brockers1** [comment] 2019-06-03 20:01
Where did you grab that SS lol, it says 0 yards whereas it should be 30

**Comment by zippoking** [comment] 2019-06-03 20:07
Good Point. Maybe you are correct, 
Screenshot is from a Cataclysm Database, since there it is generic its says 0 yards.

**Comment by r1OG** [comment] 2019-06-04 11:48
The spell really should heal 5 party members as long as they are all within the 30yard range. I´m having trouble with this aswell, and it´s annoying. My mana flies when the whole party takes damage at the same time.

**Comment by giles1508** [comment] 2019-06-04 15:05
Playing a rest druid for about hmm 7 years roughly,  I can assure you 100 % that wild growth should heal 5 players within 30 yards regardless of how much hp they have,  and if there are 7 in range the ones with most missing hp get prio

**Comment by sarahkay88** [comment] 2019-06-05 18:40
https://wotlk-twinhead.twinstar.cz/?spell=53251

**Comment by Dranah** [comment] 2019-06-15 00:41
"Up to 5" means that the spell will hit 5 members as long as it can. If it cannot target them due to range, los, zoning etc, it will heal less, in every other case, it should affect all the total of 5 targets.

This bug incapacitates resto druids.

**Comment by Keader** [comment] 2019-06-18 20:56
Fixed.

**Comment by r1OG** [comment] 2019-06-18 21:47
Resto is hard to play without this working properly, my mana leaks out even before 50% of a fight, forcing me to stack spirit

**Comment by Echinaceax** [comment] 2019-06-19 09:20
> Resto is hard to play without this working properly, my mana leaks out even before 50% of a fight, forcing me to stack spirit

fixed in dev now, so will be confirmed then up in "this or next update"

**Closed** 2019-06-20 11:25 UTC
Labels: Class, Confirmed, Fixed Confirmed, Fixed in Dev, Priority-High

**Comment by giles1508** [comment] 2019-06-22 19:27
using this today and something is still very broken...  some of my ticks are for like 400,   and im literally standing in a few yards of players in an instance and its acting like they are out of LoS  its completely ignoring them  for wild growth and i can heal them all fine with other spells,  for example in vortex pinnacle now,   on the ramp  it healed 2 people when i had rejuve on 5 people so i could defo see them in LoS   and on first boss it was only hitting 3 sometimes,  i had to move around to get it to hit others and we were all pretty close,   within like 10 yards 15 most

**Comment by giles1508** [comment] 2019-06-22 19:33
dont thinkts the spell now tbh,  think its got something to do with  some of the pathing in instances
if thats the case not alot can be done :P

**Comment by giles1508** [comment] 2019-06-22 19:44
ok so last boss in vortex,   asaad,   if i target no one  it healed 4 people,  if left out the mage,    if i targetted the mage,  it healed 4 people,  left me out,,   when i targetted myself it left the mage out again,  this is without anyone moving and with everyone in 30 yards,   as i was able to target and heal the mage with it,   just not sure, maybe terrain bugs ,  who knows,   maybe its not going 30 yards,  need to test it a bit more to know for sure,   ill keep trying in these heroics  :D
