### ISSUE TITLE
[Hunter/Pets] Rename Issue / Certificate of Ownership

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2738] opened 2019-07-14 17:31 UTC
**Links:**
No links needed

**What is happening:**

As you rename a Hunter's pet, it shows successfully the renaming of any pet. If you dismiss it, and resummon it, it goes back to the standardized name, and is not changeable anymore.

Also broken via the Certificate of Ownership 

**What should happen:**

- [x] The pet name change should be permanent.
- [x] When you also use the Certificate of Ownership name should save permanently

**Comment by Priestelar** [comment] 2019-11-02 12:26
@Keader still an issue

**Comment by Hespericless** [comment] 2020-03-02 03:56
Still an issue, even with the Certificate of Ownership from inscription.
https://www.wowhead.com/item=43850/certificate-of-ownership

**Comment by Echinaceax** [comment] 2020-12-09 11:51
Dismiss pet ID https://classic.wowhead.com/spell=2641/dismiss-pet

**Comment by mfranca0009** [comment] 2021-02-02 21:05
Found the issue for this problem, will fix this ASAP and test 👍

**Comment by mfranca0009** [comment] 2021-02-03 05:57
All set! 

**First Pet:**
![image](https://user-images.githubusercontent.com/26092980/106704405-196f9e80-65ba-11eb-9ebd-a477681f44ae.png)

**Second Pet:**
![image](https://user-images.githubusercontent.com/26092980/106704418-1f657f80-65ba-11eb-8ed6-16bb3ab3d45f.png)


**Second Pet After Certificate of Ownership (RENAME):**
![image](https://user-images.githubusercontent.com/26092980/106704465-30ae8c00-65ba-11eb-90cd-71e33bb15278.png)


**Tested for:**
- [x] Summon Pet, Dismiss pet - name stayed and did not reset.
- [x] Summon Pet, log-out, log back in - name stayed and did not reset.
- [x] Summon Pet, Use Certificate of Ownership Item, Dismiss pet, Summon Pet - New name set, and did not reset.

Will most likely need to be re-looked at more in-depth with #1812 because there is no specific pet type value for warlock pets and only summoned pets or hunter pets.

**Comment by Echinaceax** [comment] 2021-02-03 09:18
Retested 

- [x] mounting up, and dismounting
- [x] Portal, then resummoning pet (no need to resummon pets when going through portals now, cool) 
https://gyazo.com/434b2701cfc304ba4d9732f714a51c70

- [x] Tame pet, Renaming pet, dismissing pet, changing to different pet (broken it again) @mfranca0009 
https://gyazo.com/312c77f2d12dc1810aaafa819ec939d9

**Comment by mfranca0009** [comment] 2021-02-05 00:20
file didn't re-compile the first time, now functions properly after building again sucessfully.

**Comment by Echinaceax** [comment] 2021-02-05 00:21
confirmed fixed on PTR

**Closed** 2021-02-11 11:11 UTC
Labels: Class/Spells, Confirmed By Tester, Fixed Confirmed, Fixed in Dev
