### ISSUE TITLE
[bug/mount] 2 person vehicle mount deaths / Fall damage

### ISSUE THREAD

**Issue by jgilbert201** [WoWManiaUK/Blackwing-Lair#4810] opened 2020-10-28 09:41 UTC
**Links:**

https://youtu.be/9eSBIeU5Ljw

**What is happening:**

In Tol Barad sometimes when you are riding as a 2nd person in the x53 touring rocket and you are dismounted, you die from fall damage. I've physically had this happen to me and it happened to someone I was with last night. The difference between the two is on the video I was in the back. The last I was the main rider and dismounted by casting mindspike at a target.

From the map the points where I have seen this happen is the two red dots listen in the image below.

**What should happen:**

You shouldn't die

**Is it crashing the server?:**

No

**Other Information:**

![image](https://user-images.githubusercontent.com/273787/97419182-ab07aa00-1901-11eb-8254-0a28ff6d9254.png)

**Comment by Echinaceax** [comment] 2020-10-28 10:59
here is the mount @mfranca0009 
https://www.wowhead.com/item=54860/x-53-touring-rocket

will try and reporduce on Ptr ...update soon

**Comment by Echinaceax** [comment] 2020-10-28 12:07
Ok we reproduced it

**Test 1**

Tol Barad

1. driver had shaman buff https://classic.wowhead.com/spell=546/water-walking
2. Passanger didnt have waterwalking 
3. Followed the path from above video
4. Driver dismount
5. Passenger falls through graphics/map texture

### 6. Note: Also we tested all 2 and 3 person mounts 
(all do fall damage when jump on the mount while in water)

https://www.wowhead.com/item=54860/x-53-touring-rocket
https://www.wowhead.com/item=44234/reins-of-the-travelers-tundra-mammoth  (horde)
https://www.wowhead.com/item=44235/reins-of-the-travelers-tundra-mammoth (ally)
https://www.wowhead.com/item=83086/heart-of-the-nightwing
https://www.wowhead.com/item=41508/mechano-hog  (horde)
https://www.wowhead.com/item=44413/mekgineers-chopper (ally)

NOTE: tested https://www.wowhead.com/spell=93326/sandstone-drake
didnt happen on this one


I .app to Valk to get screenshot for report and i dead to 

Valk dead, **fall damage 124283**

![valk dead](https://user-images.githubusercontent.com/39439201/97433884-7ce49300-191e-11eb-931d-3acabf1397ae.jpg)

I .app to him coords **63.85, 23,37**

![i app to valk](https://user-images.githubusercontent.com/39439201/97433942-91289000-191e-11eb-84d9-69320a65f804.jpg)



**Test 2**

with Levitate

With and without Levitate 
Dmg taken jumping on the rocket while in water tested Tol barad and Twilight hiterlands openwater

1. mount on the 2/3 person mount while in deep water
2. passenger jump off and back on the mount
_You will Take fall damage_

![fall dmg jumping on the rocket](https://user-images.githubusercontent.com/39439201/97438732-7efe2000-1925-11eb-8cfa-aac334d301c7.jpg)

**Comment by Blametheheal** [comment] 2020-11-18 22:22
This just happened to me on a one person mount while water walking just barely off the shore to the north and east of Ironclad Garrison.

**Comment by Blametheheal** [comment] 2020-11-18 22:26
![image](https://user-images.githubusercontent.com/73043085/99595678-c0c93600-29ba-11eb-90ab-53c9256acd76.png)

**Comment by mfranca0009** [comment] 2021-02-04 01:48
This issue is highly related to position calculations and the passenger player's position not being calculated right.

For one, when you exit the vehicle, your position is at the bottom of the lake / ocean but it doesn't show this client-side. When you mount the vehicle again as passenger, you're technically mounting the vehicle from the bottom of the lake/ocean even though you're "next to" the vehicle. At this point, you're calculating fall damage because of the giant leap. This doesn't happen when you enter the vehicle on land, only when entering in water.

At the moment, hack fix is in place to prevent it, but will be looking into a better method to fix this problem properly.

**Closed as completed** 2021-02-11 11:10 UTC
Labels: Fixed in Dev - Ready to test, Fixed in Dev - Confirmed by tester, Confirmed By Tester
