### ISSUE TITLE
Wow Error on Guild Bank Opening

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2487] opened 2019-06-20 18:12 UTC
**What is happening:**
Just to know if someone else is having the same problem and should be the case of investigate. It happens several times that when i open the guild bank tab, with any of my 4 toons, the game crashes with wow error. Sometimes it happens after a while, when i'm moving stuff from a tab to another, but it's always guild bank related.

**What should happen:**
Players should not have a wow error when they open or do something in guild bank tabs.

**Comment by Sammy974** [comment] 2019-06-20 18:50
I add a screenshot of the error. It happened to me 2 miutes ago, again. I opened the guild bank for some second (just to check something) and the game crashed 30 sec after i closed it.
![Immagine](https://user-images.githubusercontent.com/45459932/59873784-0d12df80-939d-11e9-8cf2-d54334208586.jpg)

**Comment by Kitzunu** [comment] 2019-06-24 17:55
Never seen this issue.

Place your wow folder in a root drive (C:\ D:\ etc)
Remove the Read Only property from the wow folder and Realmlist.wtf

**Comment by Kitzunu** [comment] 2019-07-05 20:31
Will close this issue, if someone can confirm that this is server related and not just client being in the wrong place, feel free to reopen

**Closed by Kitzunu** 2019-07-05 20:31 UTC
Labels: Guild related

**Comment by sarahkay88** [comment] 2019-10-19 13:32
this was brought up again today - so tried again to reproduce and still couldn't get my pc to crash

**Comment by Echinaceax** [comment] 2019-10-19 13:33
retested and cant reproduce either 

i would repatch your client
