### ISSUE TITLE
[Quest] Resonating Blow - ID 26659

### ISSUE THREAD

**Issue by Lerixo** [WoWManiaUK/Blackwing-Lair#2694] opened 2019-07-08 23:42 UTC
**Links:**
https://www.wowhead.com/quest=26659/resonating-blow
from WoWHead or our Armory

**What is happening:**
After you hit the crystal, and try to jump on the platforms, your char jumps up, but the "camera falls down again, but you can slightly see the character model standing on the rock"(hard to explain) and you take damage. If you try to jump off the rocks with the dismount button, you fall from the height you've clicked on, although your camera being on the ground (it sets your camera up again) which most likely kills you. Also Aeosera isnt attackable in any way. Quest can't be completed.

**What should happen:**
You should jump from rock to rock, fighting Aeosera, (dodgin her fires by alternating rocks), and finally get quest progress through defeating her. Quest should be completeable.

**Comment by Rushor** [comment] 2019-07-09 08:44
duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/1993

**Closed by Rushor** 2019-07-09 08:44 UTC
Labels: Duplicate
