### ISSUE TITLE
[Race- Custom content] Goblin - Mall stone and MPs not issued upon turning 10

### ISSUE THREAD

**Issue by polymorphism98** [WoWManiaUK/Blackwing-Lair#4500] opened 2020-05-13 11:30 UTC
**Links:** https://wow-reign.com/forum/viewtopic.php?f=22&t=19

**What is happening:**
I turned level 10 today on my new Goblin char named: Encapsulate(priest). I did not receive the Mall stone and the MPs directly, even though my bag had enough space. 

**What should happen:** Player must receive the Mall Stone and MPs upon turning 10.

**Is it crashing the server?:** No

**Other Information:** I had a brief chat with GM Zinius. We feel that this might be a Goblin related issue. Hence reporting here for further verification and if anything can be done for the MPs, that I did not receive.

PS: I have already acquired the mall stone from an inn keeper.

**Comment by Echinaceax** [comment] 2020-05-13 11:53
Confirmed on the 1-10 missing MPs 

![no mp given](https://user-images.githubusercontent.com/39439201/81808708-66897d00-9520-11ea-8e15-41a0c14efd18.jpg)

On the mallstone issue 
We had this changed because Goblins where lvling to fast at weekends and porting out without completing the Goblin startzone questline, once a goblin completes Kezan they are ported to Orgrimmar where they can get the mallstone from innkeeper yes :)

goblins get the mallstone at 20 and MP fine at 20

![got both at 20 tho](https://user-images.githubusercontent.com/39439201/81809236-545c0e80-9521-11ea-9b68-f671887664ec.jpg)

### So MP missing only from 1-10 
level 10 Goblins should recieve 5MPs 
bloodelf did 

![bloodelf 5mp](https://user-images.githubusercontent.com/39439201/81809700-0dbae400-9522-11ea-9741-12637c58a3cd.jpg)

**Comment by Echinaceax** [comment] 2020-05-15 10:43
Thanks @wow-mania 

Confirmed fixed on dev 

![gobi mp](https://user-images.githubusercontent.com/39439201/82042463-30780480-96aa-11ea-91e8-1d5f84fc9b34.jpg)


updated to live hotfix, can close this

**Closed as completed** 2020-05-20 14:21 UTC
Labels: Fixed in Dev - Ready to test, Fixed in Dev - Confirmed by tester, Confirmed By Tester
