### ISSUE TITLE
[Profession/Crash] Fishing (bloodelf male)

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2551] opened 2019-06-24 13:43 UTC
**What is happening:**

Everytime I use the spell 'Fishing (ID 7620), my game crashes. 

I'am currently fishing lvl 1/525 and I tryed to fish in 
- Mount Hyjal at Sulfuron's Spike
- Orgrimmar in the Valley of Wisdom
- Tol Barad near horde' camp

I don't know what is causing the bug since other people seems like to be able to fish ?

Screenshot of the WoW-Error:
https://puu.sh/DK6HL/e537998048.png

[World of Warcraft 2019-06-24 15-37-18.zip](https://github.com/WoWManiaUK/Blackwing-Lair/files/3321067/World.of.Warcraft.2019-06-24.15-37-18.zip)

**Comment by wow-mania** [comment] 2019-06-24 15:38
First you don't have the latest client. 
Second you should never keep the client on directories controlled by windows.

You need to do the following:

1. Move the wow client to the root of your driver (Ex.: c:\wow-reign)
2. Make sure that the file realmlist.wtf is NOT read-only
3. Make sure the client folder is not read-only either
4. Add the client folder to the list of exceptions of your anti-virus
5. Start Launcher as Admin

**Comment by Rushor** [comment] 2019-06-24 15:50
https://github.com/TrinityCore/TrinityCore/issues/11788

added that fix

**Comment by Nirvanum** [comment] 2019-07-08 15:52
The problem persists, even today, although I have followed all the suggestions

**Comment by Echinaceax** [comment] 2019-07-17 12:25
@Rushor still issues regarding crashing #2754 ive closed the new report and reopened this one ok

**Comment by Denrunmt** [comment] 2019-07-19 15:06
It seems its a race bug. All the people that have that problem are Blood Elfs as far as i know. I tested it with all my chars. I got orcs, taurens and 2 blood elfs. Everything worked except the blood elfs. So me and the guys think its for Blood elfs mostly.

**Comment by Kladenets** [comment] 2019-07-21 16:38
I have got a Blood Elf Female, i didnt get this error.

**Comment by Denrunmt** [comment] 2019-07-23 15:00
Yeah, I noticed that it doesn't happen with every single Blood Elf, but mostly they get the error.

**Comment by Dranah** [comment] 2019-08-04 00:41
Confirmed, some male blood elf racial discrimination. Specifically Male blood elves crash when attempting to fish, regardless of class.

**Comment by Echinaceax** [comment] 2019-09-07 13:26
@Rushor any ETA in this please ?

**Comment by Rushor** [comment] 2019-09-16 20:15
![I](https://i.imgur.com/iHDhaMC.jpg)

works fine for me on dev

**Comment by Rushor** [comment] 2019-09-25 21:12
no idea guys, @Keader you know sth?

**Comment by Echinaceax** [comment] 2019-09-26 00:26
its very odd @Rushor

**Comment by Nirvanum** [comment] 2019-09-26 21:09
Try with Bloodelf male with horse tail hairstyle..

**Comment by Rushor** [comment] 2019-11-17 15:58
we cannot fix this - it's not server side

**Comment by Belkros** [comment] 2019-11-30 20:42
Hello all. 
I tried everything from the list above.
Nothing is working for me, still getting the error.

**Comment by Echinaceax** [comment] 2020-04-30 09:10
bugged again due to new client update 1.1 

confirmed on live

Male blood elf 
Brown hair 
long hair style

![pala long hair brown](https://user-images.githubusercontent.com/39439201/80694097-4eebd680-8ad4-11ea-9871-125ace4e0d98.jpg)


![fisher error again](https://user-images.githubusercontent.com/39439201/80693379-316a3d00-8ad3-11ea-88a2-d02481bd517a.jpg)

**Comment by Echinaceax** [comment] 2020-07-07 06:13
Any update on this issue, i had Janitor also test this and he also crashed with the male bloodelf test char 

@wow-mania did you manage to sort out why ?

**Comment by Echinaceax** [comment] 2021-01-12 12:42
Still an issue

**Comment by Echinaceax** [comment] 2021-05-13 10:40
added to main fishing report #5181

**Comment by mfranca0009** [comment] 2021-05-20 21:17
Fixed but waiting on the client update 👍

**Comment by Echinaceax** [comment] 2021-05-22 15:18
confirmed fixed in ptr

**Closed** 2021-05-28 14:34 UTC
Labels: Client, Confirmed By Tester, Fixed in Dev - Confirmed by tester, Fixed in Dev - Ready to test, Priority-High, Regression
