### ISSUE TITLE
[Object] Tiffin Ellerian Wrynn Memorial -display - Stormwind

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#1206] opened 2019-03-30 15:28 UTC
**Links:**
https://www.wowhead.com/object=206500/tiffin-ellerian-wrynn-memorial

**What is happening:**
When the plaque to read it, it displays item page missing.

**What should happen:**
should read.
Tiffin Ellerian Wrynn 
Queen of Stormwind 
Fair and just, a wit as quick as her smile. 
May the Light inherit your warmth, for our world grows cold in your absence.

**Comment by Kitzunu** [comment] 2019-03-30 16:07
Duplicate of https://github.com/WoWManiaUK/Blackwing-Lair/issues/1191

**Closed by Kitzunu** 2019-03-30 16:07 UTC
