### ISSUE TITLE
[Quest] Lycanthoth the Corruptor - ID 25272- Cutscene stuck - (Ally) - Mount Hyjal

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#248] opened 2018-12-20 21:56 UTC
quest - https://www.wowhead.com/quest=25272/lycanthoth-the-corruptor
npc - https://www.wowhead.com/npc=39432
After slaying the mob your are then suppose to be able to speak with the spirit to complete quest, however he just respawns and u are drawn into an endless cycle of killing him over and over again
![world of warcraft 20_12_2018 21_34_57_li](https://user-images.githubusercontent.com/42302580/50313039-0fee4f80-04a2-11e9-806d-05bbdb4d9c8e.jpg)

**Comment by Saintres** [comment] 2019-03-04 22:33
tried to do this quest today too.
Didnt work

**Comment by Dranah** [comment] 2019-05-12 17:59
This quest now properly spawns the https://www.wowhead.com/npc=39622/spirit-of-logosh when you kill Lycanthoth. 
![WoWScrnShot_051219_194646](https://user-images.githubusercontent.com/31132743/57585922-b2a97800-74ee-11e9-9b45-23e51b6954a5.jpg)
It's a minor issue that Lycanthoth is always spawned and does not need you to use the quest item, i guess we can live with that....
However, the problem is that when handing in the quest, the cinematic that should make you ride to the shrine with the wolf gets stuck at this point with the wolf not moving. You need to alt f4 to exit the game, you cannot cancel the cinematic or get out of it in any other way.
![WoWScrnShot_051219_163714](https://user-images.githubusercontent.com/31132743/57585987-2c416600-74ef-11e9-9ed3-f4b9d6891da4.jpg)

After you get back into the game, the Spirit of Lo'gosh you spawned is gone and you cant accept the next quest.

**Comment by giles1508** [comment] 2019-06-01 16:35
![WoWScrnShot_060119_172924](https://user-images.githubusercontent.com/50211643/58751157-de3ad500-8492-11e9-8cbe-39561546fa03.jpg)

the problem im facing at the moment is,  when the cutscene kicks in and you have to alt f4 to get out,   the cutscene is supposed to free these guys and only then are you supposed to be able to get the quests they are currently freely handing out,   and the trouble with taking these quests out of order is that your running into bugs that are pretty much only there cause the quests ARENT meant to be done,  as the prequests havent been done,  but because almost everyone is just taking every quest they see just to get them done,  and not knowing the correct order,  which in the long run is creating more work,  these quests that arent meant to be available really need to be removed when possible,  as its just causing more issues by having them active when the prequests havent been done,  im more than happy to work directly with the quest devs with the proper order and chains so we can get these perfect,   i understand its hard levelling,  but its going to be even harder when all these chains work and you cant do them as your locked in a phase because you have jumped to the next block of quests without doing the prequests

**Comment by giles1508** [comment] 2019-06-01 16:40
![WoWScrnShot_060119_173922](https://user-images.githubusercontent.com/50211643/58751253-38886580-8494-11e9-847e-be06c49df763.jpg)

and as you see,  these same 3 NPC's are not only still in thier cages,  but they are also in their spawn points after being released,  so you have the same npcs in 2 different locations,  with the exact same quests

**Comment by Dranah** [comment] 2019-06-04 16:57
The phasing issue does not belong here. One issue, one report.

**Comment by jarvik76** [comment] 2019-10-06 00:12
Did this quest today, the Spirit of Logosh https://www.wowhead.com/npc=39622/spirit-of-logosh was not spawned when you kill Lycanthoth.

**Comment by Rushor** [comment] 2019-10-08 12:14
> Did this quest today, the Spirit of Logosh https://www.wowhead.com/npc=39622/spirit-of-logosh was not spawned when you kill Lycanthoth.

fixed now. Strange stuck aura also removed now.

ID - 87338 Ride Vehicle was the reason for it.

**Comment by Rushor** [comment] 2019-10-08 12:17
cutscene will be added later.

![I](https://i.imgur.com/rdmQay8.jpg)

**Closed** 2019-10-09 10:16 UTC
Labels: Confirmed, Fixed Confirmed, Fixed in Dev, zone 80-85 Cata
